import type { OnboardingAnswers, OnboardingScreen } from './types';

export const initialAnswers: OnboardingAnswers = {
  primaryGoal: 'tone',
  useCases: ['home'],
  experienceLevel: 'self-taught',
  learningSources: ['youtube'],
  reportedSymptoms: ['fade'],
  biggestFrustration: 'recordings',
  playbackComfort: 'hate-playback',
  feedbackStyle: 'gentle',
  practiceLength: '10',
  reminderTime: 'evening',
  practiceEnvironment: ['phone-mic'],
  strainStatus: 'none',
  micPermissionStatus: 'not-requested',
};

export const onboardingScreens: OnboardingScreen[] = [
  {
    id: 'ONB-01',
    shortTitle: 'Splash',
    kind: 'splash',
    eyebrow: 'VoiceFix',
    title: 'Hear what changed.',
    body: 'A private voice lab for short checks, one useful cue, and a retry on the same take.',
    primaryAction: 'Enter the studio',
  },
  {
    id: 'ONB-02',
    shortTitle: 'Promise',
    kind: 'info',
    eyebrow: 'Six month commitment',
    title: 'Singing is built through small returns.',
    body: 'VoiceFix is a 180-day training journey. You will not prove your talent in one session; you will show up, record honestly, fix one small thing, and return tomorrow.',
    primaryAction: 'Start the 6-month journey',
    bullets: ['A fixed 24-week path', 'One monthly grace day', 'One retry every session'],
  },
  {
    id: 'ONB-03',
    shortTitle: 'Not karaoke',
    kind: 'info',
    eyebrow: 'Different loop',
    title: 'This is not a karaoke score.',
    body: 'Karaoke asks if you hit the note. VoiceFix asks what probably made the note unstable, then lets you retry the same task.',
    primaryAction: 'Continue',
    comparison: [
      { label: 'Karaoke apps', detail: 'Did you hit the note?', icon: 'music-note' },
      { label: 'VoiceFix', detail: 'What changed between takes?', icon: 'graphic-eq' },
      { label: 'Your plan', detail: 'One cue, same drill, retry.', icon: 'refresh' },
    ],
  },
  {
    id: 'ONB-04',
    shortTitle: 'Goal',
    kind: 'single',
    eyebrow: 'Personal goal',
    title: 'What do you most want to fix first?',
    body: 'This chooses the first lane of your plan.',
    primaryAction: 'Continue',
    dataKey: 'primaryGoal',
    options: [
      { id: 'pitch', label: 'Hit notes more reliably', detail: 'I miss, slide, or cannot lock into the note.', icon: 'tune' },
      { id: 'tone', label: 'Stop sounding shaky or thin', detail: 'My recorded voice feels unstable or small.', icon: 'graphic-eq' },
      { id: 'range', label: 'Sing higher without pushing', detail: 'Higher notes feel tight or forced.', icon: 'north-east' },
      { id: 'confidence', label: 'Feel less embarrassed recording', detail: 'I want private practice that feels survivable.', icon: 'lock' },
      { id: 'habit', label: 'Build a consistent habit', detail: 'I need a repeatable plan, not random drills.', icon: 'calendar-today' },
    ],
  },
  {
    id: 'ONB-05',
    shortTitle: 'Use case',
    kind: 'multi',
    eyebrow: 'Where this voice goes',
    title: 'Where do you want to use your voice?',
    body: 'Your plan should match the situations that actually matter to you.',
    primaryAction: 'Continue',
    dataKey: 'useCases',
    options: [
      { id: 'home', label: 'Singing alone at home', detail: 'Private practice, low pressure.', icon: 'home' },
      { id: 'karaoke', label: 'Karaoke', detail: 'Confidence with familiar songs.', icon: 'mic' },
      { id: 'group', label: 'Choir or group singing', detail: 'Blend, pitch, and steadiness.', icon: 'groups' },
      { id: 'covers', label: 'Posting covers online', detail: 'Cleaner takes and repeatable progress.', icon: 'movie' },
      { id: 'lessons', label: 'Preparing for lessons', detail: 'Arrive with clearer questions.', icon: 'school' },
      { id: 'speaking', label: 'Speaking or mic confidence', detail: 'Voice control outside songs.', icon: 'record-voice-over' },
    ],
  },
  {
    id: 'ONB-06',
    shortTitle: 'Experience',
    kind: 'single',
    eyebrow: 'Starting point',
    title: 'What is your vocal experience?',
    body: 'This controls difficulty and how much explanation appears.',
    primaryAction: 'Continue',
    dataKey: 'experienceLevel',
    options: [
      { id: 'beginner', label: 'Total beginner', detail: 'I do not have a steady practice routine yet.', icon: 'radio-button-unchecked' },
      { id: 'self-taught', label: 'Self-taught', detail: 'I use videos, apps, songs, or trial and error.', icon: 'explore' },
      { id: 'returning', label: 'Returning after a break', detail: 'I have sung before and want structure again.', icon: 'history' },
      { id: 'lessons-before', label: 'Some lessons before', detail: 'I know a few terms but need a loop.', icon: 'school' },
      { id: 'musician', label: 'Musician, not vocally trained', detail: 'My ear may be ahead of my voice.', icon: 'piano' },
    ],
  },
  {
    id: 'ONB-07',
    shortTitle: 'History',
    kind: 'multi',
    eyebrow: 'Learning history',
    title: 'What have you tried already?',
    body: 'This helps VoiceFix avoid becoming one more disconnected exercise list.',
    primaryAction: 'Continue',
    dataKey: 'learningSources',
    options: [
      { id: 'youtube', label: 'YouTube lessons', detail: 'Useful, but hard to personalize.', icon: 'smart-display' },
      { id: 'tuner', label: 'Tuner or pitch apps', detail: 'Good signal, little explanation.', icon: 'show-chart' },
      { id: 'karaoke-apps', label: 'Karaoke apps', detail: 'Fun, but often score-first.', icon: 'music-note' },
      { id: 'coach', label: 'Teacher or coach', detail: 'Human feedback, less daily instrumentation.', icon: 'person' },
      { id: 'choir', label: 'Choir practice', detail: 'Group context and repetition.', icon: 'groups' },
      { id: 'songs', label: 'Mostly singing songs', detail: 'Real material, but hard to isolate causes.', icon: 'library-music' },
    ],
  },
  {
    id: 'ONB-08',
    shortTitle: 'Symptoms',
    kind: 'multi',
    eyebrow: 'Voice clues',
    title: 'What sounds wrong most often?',
    body: 'Pick everything that feels familiar. The voice check will cross-check it gently.',
    primaryAction: 'Continue',
    dataKey: 'reportedSymptoms',
    options: [
      { id: 'fade', label: 'My sound fades at the end', detail: 'Often useful for airflow routing.', icon: 'air' },
      { id: 'pitch-drift', label: 'I drift flat or sharp', detail: 'Useful for pitch-match drills.', icon: 'trending-down' },
      { id: 'wobble', label: 'My notes wobble', detail: 'We may start with smaller targets.', icon: 'waves' },
      { id: 'breathy', label: 'My voice sounds breathy', detail: 'Can affect stability and clarity.', icon: 'blur-on' },
      { id: 'squeezed', label: 'My voice sounds harsh or squeezed', detail: 'Plan should avoid pushing.', icon: 'pan-tool-alt' },
      { id: 'crack', label: 'I crack when going higher', detail: 'Range work must stay gentle.', icon: 'report-problem' },
      { id: 'timing', label: 'I rush or lose timing', detail: 'Echo drills can stay slower.', icon: 'timer' },
      { id: 'unknown', label: 'I cannot tell what is wrong', detail: 'That is exactly what the baseline is for.', icon: 'help-outline' },
    ],
  },
  {
    id: 'ONB-09',
    shortTitle: 'Frustration',
    kind: 'single',
    eyebrow: 'Hardest part',
    title: 'What feels most frustrating right now?',
    body: 'Technique and emotion both affect whether you keep practicing.',
    primaryAction: 'Continue',
    dataKey: 'biggestFrustration',
    options: [
      { id: 'what-to-practice', label: 'I do not know what to practice', detail: 'The plan should choose the next drill.', icon: 'route' },
      { id: 'recordings', label: 'I sound worse on recordings', detail: 'Playback needs to be gentle and useful.', icon: 'hearing-disabled' },
      { id: 'needs-guide', label: 'I match notes only with a guide', detail: 'Reference fading will matter later.', icon: 'track-changes' },
      { id: 'embarrassed', label: 'I feel embarrassed practicing', detail: 'Tiny private wins should come first.', icon: 'lock' },
      { id: 'inconsistent', label: 'I improve and lose it again', detail: 'Repeatable baselines can show what moved.', icon: 'sync-problem' },
    ],
  },
  {
    id: 'ONB-10',
    shortTitle: 'Playback',
    kind: 'single',
    eyebrow: 'Playback comfort',
    title: 'How do you feel about hearing recordings?',
    body: 'VoiceFix can keep playback optional while still comparing your takes.',
    primaryAction: 'Continue',
    dataKey: 'playbackComfort',
    options: [
      { id: 'hate-playback', label: 'I hate hearing my recorded voice', detail: 'No surprise auto-play after takes.', icon: 'volume-off' },
      { id: 'if-helpful', label: 'I can listen if it helps', detail: 'Use playback after the plain note.', icon: 'hearing' },
      { id: 'before-after', label: 'I want before/after playback', detail: 'Make comparisons more visible.', icon: 'compare-arrows' },
      { id: 'metrics-first', label: 'Metrics first, playback later', detail: 'Show signal notes before audio.', icon: 'analytics' },
    ],
  },
  {
    id: 'ONB-11',
    shortTitle: 'Feedback',
    kind: 'single',
    eyebrow: 'Feedback style',
    title: 'How should feedback sound at first?',
    body: 'Same analysis, different language temperature.',
    primaryAction: 'Continue',
    dataKey: 'feedbackStyle',
    options: [
      { id: 'gentle', label: 'Gentle and encouraging', detail: 'Small cue, low pressure.', icon: 'favorite-border' },
      { id: 'direct', label: 'Direct but not harsh', detail: 'Clear observation, fast next action.', icon: 'gps-fixed' },
      { id: 'technical', label: 'Technical once I understand basics', detail: 'Plain note first, signal detail second.', icon: 'memory' },
    ],
  },
  {
    id: 'ONB-12',
    shortTitle: 'Practice time',
    kind: 'single',
    eyebrow: 'Routine fit',
    title: 'How much practice should the plan expect?',
    body: 'A plan you repeat beats a plan that sounds impressive once.',
    primaryAction: 'Continue',
    dataKey: 'practiceLength',
    options: [
      { id: '5', label: '5 minutes most days', detail: 'Short checks and one retry.', icon: 'timer' },
      { id: '10', label: '10-12 minutes', detail: 'Three drills, one retry each.', icon: 'calendar-today' },
      { id: '20', label: '20 minutes', detail: 'More repetitions and journal depth.', icon: 'all-inclusive' },
      { id: 'unsure', label: 'I am not sure yet', detail: 'Start small and adjust later.', icon: 'help-outline' },
    ],
  },
  {
    id: 'ONB-13',
    shortTitle: 'Environment',
    kind: 'multi',
    eyebrow: 'Practice environment',
    title: 'Where will you usually practice?',
    body: 'This prevents the first recordings from feeling awkward or impossible.',
    primaryAction: 'Continue',
    dataKey: 'practiceEnvironment',
    options: [
      { id: 'quiet-room', label: 'Quiet room', detail: 'Best for full checks and playback.', icon: 'meeting-room' },
      { id: 'shared-space', label: 'Shared space', detail: 'Keep tasks shorter and softer.', icon: 'weekend' },
      { id: 'car', label: 'Car', detail: 'Good privacy, different acoustics.', icon: 'directions-car' },
      { id: 'headphones', label: 'Headphones available', detail: 'Reference tones will be clearer.', icon: 'headphones' },
      { id: 'phone-mic', label: 'Phone mic only', detail: 'Default baseline path.', icon: 'phone-iphone' },
      { id: 'quiet-practice', label: 'I need to practice quietly', detail: 'Favor hums and soft drills first.', icon: 'notifications-off' },
    ],
  },
  {
    id: 'ONB-14',
    shortTitle: 'Safety',
    kind: 'single',
    eyebrow: 'Voice health',
    title: 'Any pain, tightness, or pushing?',
    body: 'VoiceFix is practice feedback, not medical advice. If singing hurts, stop and consider a qualified professional.',
    primaryAction: 'Continue',
    dataKey: 'strainStatus',
    options: [
      { id: 'none', label: 'No pain or strain', detail: 'Normal beginner difficulty is okay.', icon: 'check-circle' },
      { id: 'tight', label: 'Sometimes tight', detail: 'Keep range modest and check comfort.', icon: 'warning-amber' },
      { id: 'pain', label: 'Pain when singing', detail: 'Start with gentle reset and referral copy.', icon: 'medical-services' },
      { id: 'unsure', label: 'Not sure', detail: 'Use cautious defaults.', icon: 'help-outline' },
    ],
  },
  {
    id: 'ONB-15',
    shortTitle: 'Privacy',
    kind: 'info',
    eyebrow: 'Privacy and mic trust',
    title: 'You control when VoiceFix listens.',
    body: 'VoiceFix listens only during exercises you start. Clips are private by default and can be deleted later.',
    primaryAction: 'Continue to microphone',
    bullets: ['No surprise recording', 'Private clips by default', 'Saved only for your journal'],
  },
  {
    id: 'ONB-16',
    shortTitle: 'Mic',
    kind: 'permission',
    eyebrow: 'Microphone',
    title: 'Allow the mic for the voice check.',
    body: 'This prototype simulates permission so you can review the onboarding flow. The production app will request the OS microphone permission here.',
    primaryAction: 'Allow microphone',
    secondaryAction: 'Continue without voice check',
    dataKey: 'micPermissionStatus',
  },
  {
    id: 'ONB-17',
    shortTitle: 'Check intro',
    kind: 'voiceIntro',
    eyebrow: 'Voice check',
    title: 'Five tiny recordings build the first plan.',
    body: 'This is not a grade. We listen for patterns that suggest the safest first focus.',
    primaryAction: 'Start voice check',
    bullets: ['Stop if anything hurts', 'Short samples only', 'No celebrity comparison'],
  },
  {
    id: 'ONB-18',
    shortTitle: 'Hiss',
    kind: 'recording',
    eyebrow: 'Voice check 1 of 5',
    title: 'Steady hiss',
    primaryAction: 'Save sample',
    recording: {
      index: 1,
      title: 'Steady hiss',
      instruction: 'Take a comfortable breath. Make a soft "sss" and keep it even until you naturally stop.',
      listensFor: ['Duration', 'Evenness', 'Drop-off near the end'],
      icon: 'air',
    },
  },
  {
    id: 'ONB-19',
    shortTitle: 'Hum',
    kind: 'recording',
    eyebrow: 'Voice check 2 of 5',
    title: 'Gentle hum',
    primaryAction: 'Save sample',
    recording: {
      index: 2,
      title: 'Gentle hum',
      instruction: 'Hum softly on one comfortable pitch. It should feel easy, not loud.',
      listensFor: ['Stability', 'Roughness proxy', 'Comfort signal'],
      icon: 'blur-on',
    },
  },
  {
    id: 'ONB-20',
    shortTitle: 'Sustain',
    kind: 'recording',
    eyebrow: 'Voice check 3 of 5',
    title: 'Sustained ah',
    primaryAction: 'Save sample',
    recording: {
      index: 3,
      title: 'Sustained ah',
      instruction: 'Sing "ah" on one comfortable note for about five seconds.',
      listensFor: ['Pitch drift', 'Wobble', 'End-of-note fade'],
      icon: 'graphic-eq',
    },
  },
  {
    id: 'ONB-21',
    shortTitle: 'Pitch match',
    kind: 'recording',
    eyebrow: 'Voice check 4 of 5',
    title: 'Pitch match',
    primaryAction: 'Save sample',
    secondaryAction: 'Play tone',
    recording: {
      index: 4,
      title: 'Pitch match',
      instruction: 'Listen to the note. Sing "ah" and try to match it.',
      listensFor: ['Sharp / flat tendency', 'Finding the pitch', 'Stability after match'],
      icon: 'track-changes',
    },
  },
  {
    id: 'ONB-22',
    shortTitle: 'Echo',
    kind: 'recording',
    eyebrow: 'Voice check 5 of 5',
    title: 'Three-note echo',
    primaryAction: 'Save sample',
    secondaryAction: 'Play pattern',
    recording: {
      index: 5,
      title: 'Three-note echo',
      instruction: 'Listen to three slow notes, then echo them on "ah."',
      listensFor: ['Hardest note', 'Movement stability', 'Timing confidence'],
      icon: 'multiline-chart',
    },
  },
  {
    id: 'ONB-23',
    shortTitle: 'Analysis',
    kind: 'analysis',
    eyebrow: 'Building plan',
    title: 'Reading your answers and voice samples.',
    body: 'VoiceFix is choosing the first focus, not judging your talent.',
    primaryAction: 'View diagnostic recap',
    bullets: ['Reading your goals', 'Checking comfort and safety', 'Comparing the five samples', 'Building your first 14 days'],
  },
  {
    id: 'ONB-24',
    shortTitle: 'Recap',
    kind: 'recap',
    eyebrow: 'Diagnostic recap',
    title: 'Here is what the baseline suggests.',
    body: 'Careful wording matters: this is a starter hypothesis, not a full diagnosis.',
    primaryAction: 'See my plan',
  },
  {
    id: 'ONB-25',
    shortTitle: 'Plan',
    kind: 'plan',
    eyebrow: '14-day plan',
    title: 'Your first plan is ready.',
    primaryAction: 'Preview first session',
  },
  {
    id: 'ONB-26',
    shortTitle: 'Session',
    kind: 'sessionPreview',
    eyebrow: 'First session',
    title: 'Three drills. One retry each.',
    body: 'Each drill has the same loop: record, get one note, try once more, compare to yourself.',
    primaryAction: 'Continue',
  },
  {
    id: 'ONB-27',
    shortTitle: 'Reminder',
    kind: 'single',
    eyebrow: 'Daily return',
    title: 'When should VoiceFix call you back?',
    body: 'A daily voice habit works best when the app asks for the same small promise at the same time.',
    primaryAction: 'Set training time',
    dataKey: 'reminderTime',
    options: [
      { id: 'morning', label: 'Morning', detail: 'Start the day with a short voice setup.', icon: 'wb-sunny' },
      { id: 'afternoon', label: 'Afternoon', detail: 'Use a midday reset before the day gets loud.', icon: 'light-mode' },
      { id: 'evening', label: 'Evening', detail: 'Train when you can be private and consistent.', icon: 'nights-stay' },
      { id: 'custom', label: 'Choose later', detail: 'Keep the prototype default for now.', icon: 'schedule' },
    ],
  },
  {
    id: 'ONB-28',
    shortTitle: 'Ready',
    kind: 'ready',
    eyebrow: 'Ready',
    title: 'You are set.',
    body: 'Your first session is queued with a focus, three drills, and a safety reminder.',
    primaryAction: 'Start first session',
    secondaryAction: 'Do it later',
  },
];
