import type { Language } from "@/features/onboarding/types";
import { languageOptions } from "@/features/onboarding/localization";

import type { CurriculumWeek } from "./curriculum";

export type MainAppLanguage = Language;

export const mainAppLanguageOptions = languageOptions.map((option) => ({
  id: option.id,
  flag: option.flag,
  label: option.name,
  shortLabel: option.abbr,
}));

const baseMainAppText = {
  en: {
    tabs: {
      today: "Today",
      journey: "Journey",
      coach: "Coach",
      journal: "Milestones",
      settings: "Settings",
    },
    common: {
      day: "Day",
      of: "of",
      week: "Week",
      loading: "Loading your Rehear journey...",
      grace: "grace",
      ready: "Ready",
      used: "Used",
      today: "today",
      streak: "streak",
      dayStreak: "day streak",
      graceDay: "grace day",
      firstTake: "first take",
      retry: "retry",
    },
    today: {
      trainingSession: "Training session",
      introBody:
        "Small honest repetitions are how the voice changes. Today, record once, improve one thing, then retry the exact same drill.",
      warmUp: "Warm-up",
      mainDrill: "Main drill",
      retryRule: "Retry rule",
      retryRuleDetail: "Same task, one cue, one comparison.",
      startRecording: "Start recording",
      recordFirstTake: "Record the first take.",
      storesLocally:
        "Rehear stores this take locally for the retry comparison.",
      readyToRecord: "Ready to record",
      startFirstTake: "Start first take",
      stopFirstTake: "Stop first take",
      oneThing: "One thing to try.",
      whatWeHeard: "What we heard",
      whatItMeans: "What it often means",
      oneFix: "One fix",
      retrySameDrill: "Retry same drill",
      retryUnchanged: "Retry, unchanged.",
      retryBody: "Same drill. Same target. Only the cue changes.",
      secondTakeComparison: "Second take comparison",
      readyToRetry: "Ready to retry",
      startRetry: "Start retry",
      stopRetry: "Stop retry",
      dayComplete: "Day complete.",
      savedFallback: "The app saved this progress to Milestones.",
      recordedTakes: "Recorded takes",
      backToToday: "Back to Today",
      todaysSession: "Today’s session",
      recordCueRetry: "Record, get one cue, retry.",
      practiceAgain: "Practice again",
      startTraining: "Start training",
      micUnavailableTitle: "Microphone unavailable",
      micUnavailableBody: "Allow microphone access to record real takes.",
      micSetupFailed:
        "Microphone setup failed. You can still review the flow, but real recording is unavailable.",
      recordStartFailed:
        "Recording could not start. Check mic permission and try again.",
      recordSaveFailed:
        "Recording could not be saved. Try again with a shorter take.",
      placementReason:
        "Onboarding recommended this starting point inside the roadmap.",
      analyzing: "Analyzing",
      analyzingBody: "Reviewing your take…",
      analysisUnavailable: "Analysis unavailable",
      analysisUnavailableBody:
        "We could not analyze this take right now. Retry or tap Done to continue.",
      done: "Done",
      forYouTitle: "For You",
      forYouSubtitle: "Personalized picks for your singing goal",
      showDailyGoal: "Show daily goal",
      dailyGoal: "Daily Goal",
      exercisesLabel: "Exercises",
      weekChip: "Week {number}",
      showExerciseA11y: "Show {title}",
      startExerciseA11y: "Start {title}",
      exerciseIllustrationA11y: "{title} exercise illustration",
      analyzingTake: "Analyzing take",
      goalLabel: "Goal",
      instructionsLabel: "Instructions",
      startLabel: "Start",
      readySetGoSet: "Set",
      readySetGoGo: "Go",
      back: "Back",
      closeLabel: "Close",
    },
    journey: {
      kicker: "3-month roadmap",
      title: "Your fixed Rehear journey.",
      body: "Onboarding chooses your starting point. The 12-week path stays visible, reviewable, and skippable by checkpoint.",
      currentPlacement: "Current placement",
      completeOnboarding:
        "Complete onboarding to place yourself in the curriculum.",
      review: "Review",
      current: "Current",
      locked: "Locked",
      note: "Skip-ahead checks are shown as prototype affordances. In production, they require one recording, one retry, and no pain report.",
      comingSoon: "Coming soon",
      comingSoonBody:
        "We will open this month after the Month 1 practice and analysis engine is complete.",
      monthOneOnly:
        "For now, only Month 1 breath and resonance training is available.",
      successCheck: "Success check",
      practice: "What you'll practice",
      focus: "Focus",
      how: "How",
      schedule: "Your schedule",
      scheduleBody: "Practice the same exercises every day this week.",
      safetyRules: "Safety rules",
      currentDay: "You're on {day}",
      openWeekPlan: "Opens this week's goal and training",
      next: "Next",
      testingCenterTitle: "Month {month} testing center",
      monthlyCheckpoint: "Monthly checkpoint",
      monthlyCheckpointPassed: "Monthly checkpoint · passed",
    },
    testing: {
      micUnavailableTitle: "Microphone unavailable",
      micUnavailableBody: "The testing center needs real recording permission.",
      recordStartFailedTitle: "Recording could not start",
      pleaseTryAgain: "Please try again.",
      recordSaveFailed: "Recording could not be saved. Try again.",
      analysisServerFailed:
        "Could not reach the analysis server. Try again.",
      monthEndGate: "Month-end gate",
      monthOneIntro:
        "Record and analyze each check to confirm Month 1 foundations are stable.",
      comingSoonIntro: "This testing center is opening soon.",
      progress: "Progress",
      alreadyPassed: "Already passed",
      monthOnePassed: "Month 1 test passed",
      readyForNextMonth: "You are ready to open the next month.",
      monthOneOnly: "Only Month 1 testing is available right now.",
      qualityInsufficient:
        "The recording quality was not enough. Record a clearer take.",
      passedNext: "Passed. Move to the next check.",
      statusPassed: "Passed",
      statusRetry: "Retry",
      statusReady: "Ready",
      analyzing: "Analyzing",
      waiting: "Waiting",
      stopRecording: "Stop recording",
      recordAgain: "Record again",
      start: "Start",
      passMonthTest: "Pass Month 1 test",
      retake: "Retake",
      stop: "Stop",
      readyToUnlockNextMonth:
        "This month is ready to unlock the next month.",
    },
    journal: {
      kicker: "Milestones",
      title: "Achievements from steady practice.",
      body: "Rehear turns completed exercises, daily goals, streaks, and checkpoints into local progress badges.",
      emptyTitle: "No achievements earned yet.",
      emptyBody:
        "Complete today’s training loop to start unlocking exercise, goal, and streak badges.",
      latestComparison: "Latest badge",
      firstTake: "First take",
      retry: "Retry",
      first: "First",
      savedLocally: "saved locally",
      noUri: "no URI",
      monthlyCheckpoints: "Monthly checkpoints",
      checkpointOne: "Month 1 breath and resonance",
      checkpointTwo: "Month 2 vocal control",
      checkpointThree: "Month 3 final song comparison",
      open: "Open",
      later: "Later",
    },
    settings: {
      kicker: "Settings",
      title: "Keep the promise realistic.",
      body: "These controls tune habit pressure without changing the fixed curriculum.",
      dailyTraining: "Daily training",
      reminderTime: "Reminder time",
      notificationTone: "Notification tone",
      sessionLength: "Session length",
      habitRules: "Habit rules",
      graceCopy:
        "One missed day per calendar month can use a grace day. The streak survives; the 90-day journey never resets.",
      currentStreak: "current streak",
      bestStreak: "best streak",
      other: "Other",
      permissions: "Permissions",
      notifications: "Notifications",
      microphone: "Microphone",
      permissionAllowed: "Allowed",
      permissionDenied: "Denied",
      permissionNotSet: "Not set",
      safetyReminder: "Safety reminder",
      safetyReminderValue: "Stop if your throat hurts",
      language: "Language",
      audio: "Audio",
      audioValue: "Real local recording",
      analyzeAudioFile: "Analyze audio file",
      analyzeAudioFileValue: "Send file to resonance analyzer",
      analyzeAudioTitle: "Analysis result",
      analyzeAudioFailedTitle: "Analysis failed",
      analyzeAudioFailedBody:
        "Start the analysis server and try again with an audio file.",
      analysisCompatibilityFallback:
        "Server rejected resonance_vowel, so Rehear retried with mmm_resonance.",
      waitingForAnalysis:
        "Waiting for server analysis. One cue will appear shortly.",
      localFallbackUsed:
        "Server unavailable, so Rehear used the local fallback.",
      retryAnalysisTitle: "Retry analysis result",
      firstAnalysisTitle: "First take analysis result",
      deleteAccount: "Delete account",
    },
  },
  ko: {
    tabs: {
      today: "오늘",
      journey: "여정",
      coach: "코치",
      journal: "마일스톤",
      settings: "설정",
    },
    common: {
      day: "일차",
      of: "/",
      week: "주차",
      loading: "Rehear 여정을 불러오는 중...",
      grace: "유예일",
      ready: "준비됨",
      used: "사용됨",
      today: "오늘",
      streak: "연속",
      dayStreak: "연속일",
      graceDay: "유예일",
      firstTake: "첫 테이크",
      retry: "재시도",
    },
    today: {
      trainingSession: "훈련 세션",
      introBody:
        "목소리는 작은 반복으로 달라집니다. 오늘은 한 번 녹음하고, 한 가지만 고친 뒤, 같은 드릴을 다시 합니다.",
      warmUp: "워밍업",
      mainDrill: "중심 드릴",
      retryRule: "재시도 규칙",
      retryRuleDetail: "같은 과제, 한 가지 힌트, 한 번의 비교.",
      startRecording: "녹음 시작",
      recordFirstTake: "첫 테이크를 녹음하세요.",
      storesLocally:
        "Rehear는 재시도 비교를 위해 이 테이크를 기기에 저장합니다.",
      readyToRecord: "녹음 준비됨",
      startFirstTake: "첫 테이크 시작",
      stopFirstTake: "첫 테이크 정지",
      oneThing: "한 가지를 시도해보세요.",
      whatWeHeard: "들린 점",
      whatItMeans: "흔한 의미",
      oneFix: "한 가지 수정",
      retrySameDrill: "같은 드릴 다시 하기",
      retryUnchanged: "그대로 다시 시도하세요.",
      retryBody: "같은 드릴, 같은 목표입니다. 달라지는 것은 힌트 하나뿐입니다.",
      secondTakeComparison: "두 번째 테이크 비교",
      readyToRetry: "재시도 준비됨",
      startRetry: "재시도 시작",
      stopRetry: "재시도 정지",
      dayComplete: "오늘 훈련 완료.",
      savedFallback: "진행 상황이 마일스톤에 저장되었습니다.",
      recordedTakes: "녹음한 테이크",
      backToToday: "오늘로 돌아가기",
      todaysSession: "오늘의 세션",
      recordCueRetry: "녹음하고, 한 가지 힌트를 받고, 다시 시도합니다.",
      practiceAgain: "다시 연습하기",
      startTraining: "훈련 시작",
      micUnavailableTitle: "마이크를 사용할 수 없음",
      micUnavailableBody: "실제 테이크를 녹음하려면 마이크 접근을 허용하세요.",
      micSetupFailed:
        "마이크 설정에 실패했습니다. 흐름은 볼 수 있지만 실제 녹음은 사용할 수 없습니다.",
      recordStartFailed:
        "녹음을 시작할 수 없습니다. 마이크 권한을 확인하고 다시 시도하세요.",
      recordSaveFailed: "녹음을 저장할 수 없습니다. 더 짧게 다시 시도하세요.",
      placementReason:
        "온보딩 결과에 따라 로드맵 안의 시작점이 추천되었습니다.",
      analyzing: "분석 중",
      analyzingBody: "녹음을 검토하고 있습니다.",
      analysisUnavailable: "분석을 사용할 수 없습니다",
      analysisUnavailableBody:
        "지금은 녹음을 분석할 수 없습니다. 다시 시도하거나 완료를 눌러 계속하세요.",
      done: "완료",
      forYouTitle: "추천 훈련",
      forYouSubtitle: "오늘 목표에 맞춘 개인 훈련 카드",
      showDailyGoal: "오늘 목표 보기",
      dailyGoal: "오늘 목표",
      exercisesLabel: "훈련",
      weekChip: "{number}주",
      showExerciseA11y: "{title} 보기",
      startExerciseA11y: "{title} 시작",
      exerciseIllustrationA11y: "{title} 운동 그림",
      analyzingTake: "테이크 분석 중",
      goalLabel: "목표",
      instructionsLabel: "안내",
      startLabel: "시작",
      readySetGoSet: "대기",
      readySetGoGo: "시작",
      back: "뒤로",
      closeLabel: "닫기",
    },
    journey: {
      kicker: "3개월 로드맵",
      title: "고정된 Rehear 여정.",
      body: "온보딩은 시작점을 고릅니다. 12주 경로는 항상 보이고, 복습하거나 체크포인트에서 건너뛸 수 있습니다.",
      currentPlacement: "현재 시작점",
      completeOnboarding:
        "온보딩을 완료하면 커리큘럼 안에서 시작점이 정해집니다.",
      review: "복습",
      current: "진행중",
      locked: "잠김",
      note: "건너뛰기 체크는 프로토타입 기능 표시입니다. 실제 제품에서는 한 번 녹음, 한 번 재시도, 통증 없음 확인이 필요합니다.",
      comingSoon: "곧 열립니다",
      comingSoonBody:
        "1개월 훈련과 분석 엔진을 먼저 완성한 뒤 이 달을 열겠습니다.",
      monthOneOnly:
        "현재는 1개월 호흡과 공명 훈련만 사용할 수 있습니다.",
      successCheck: "성공 기준",
      practice: "이번 주 훈련",
      focus: "목표",
      how: "방법",
      schedule: "이번 주 일정",
      scheduleBody: "이번 주는 매일 같은 훈련을 반복합니다.",
      safetyRules: "안전 규칙",
      currentDay: "현재 {day}",
      openWeekPlan: "이번 주 목표와 훈련을 엽니다",
      next: "다음",
      testingCenterTitle: "{month}개월 테스트 센터",
      monthlyCheckpoint: "월간 체크포인트",
      monthlyCheckpointPassed: "월간 체크포인트 · 통과",
    },
    testing: {
      micUnavailableTitle: "마이크를 사용할 수 없습니다",
      micUnavailableBody: "테스트 센터는 실제 녹음 권한이 필요합니다.",
      recordStartFailedTitle: "녹음을 시작하지 못했습니다",
      pleaseTryAgain: "다시 시도해보세요.",
      recordSaveFailed: "녹음 파일을 저장하지 못했습니다. 다시 시도하세요.",
      analysisServerFailed:
        "분석 서버에 연결하지 못했습니다. 다시 시도하세요.",
      monthEndGate: "월말 확인",
      monthOneIntro:
        "각 항목을 실제로 녹음하고 분석해서 1개월 기초가 안정적인지 확인합니다.",
      comingSoonIntro: "이 테스트 센터는 곧 열립니다.",
      progress: "진행",
      alreadyPassed: "이미 통과했습니다",
      monthOnePassed: "1개월 테스트 통과",
      readyForNextMonth: "다음 달을 열 수 있는 상태입니다.",
      monthOneOnly: "현재는 1개월 테스트만 사용할 수 있습니다.",
      qualityInsufficient:
        "녹음 품질이 충분하지 않습니다. 더 선명하게 다시 녹음하세요.",
      passedNext: "통과했습니다. 다음 항목으로 가세요.",
      statusPassed: "통과",
      statusRetry: "다시",
      statusReady: "대기",
      analyzing: "분석 중",
      waiting: "대기",
      stopRecording: "녹음 중지",
      recordAgain: "다시 녹음",
      start: "시작",
      passMonthTest: "1개월 테스트 통과",
      retake: "다시 녹음",
      stop: "중지",
      readyToUnlockNextMonth: "다음 달을 열 수 있는 상태입니다.",
    },
    journal: {
      kicker: "마일스톤",
      title: "꾸준한 연습으로 얻는 성취.",
      body: "Rehear는 완료한 연습, 일일 목표, 연속 기록, 체크포인트를 로컬 배지로 보여줍니다.",
      emptyTitle: "아직 획득한 성취가 없습니다.",
      emptyBody:
        "오늘 훈련 루프를 완료하면 연습, 목표, 연속 기록 배지를 열기 시작합니다.",
      latestComparison: "최근 배지",
      firstTake: "첫 테이크",
      retry: "재시도",
      first: "첫 테이크",
      savedLocally: "기기에 저장됨",
      noUri: "저장 없음",
      monthlyCheckpoints: "월별 체크포인트",
      checkpointOne: "1개월 호흡과 공명",
      checkpointTwo: "2개월 보컬 컨트롤",
      checkpointThree: "3개월 최종 노래 비교",
      open: "열림",
      later: "나중에",
    },
    settings: {
      kicker: "설정",
      title: "현실적인 약속을 유지하세요.",
      body: "이 설정은 고정 커리큘럼은 바꾸지 않고 습관 압력만 조절합니다.",
      dailyTraining: "매일 훈련",
      reminderTime: "알림 시간",
      notificationTone: "알림 톤",
      sessionLength: "세션 길이",
      habitRules: "습관 규칙",
      graceCopy:
        "한 달에 하루는 유예일로 사용할 수 있습니다. 연속 기록은 유지되고, 90일 여정은 리셋되지 않습니다.",
      currentStreak: "현재 연속일",
      bestStreak: "최고 연속일",
      other: "기타",
      permissions: "권한",
      notifications: "알림",
      microphone: "마이크",
      permissionAllowed: "허용됨",
      permissionDenied: "거부됨",
      permissionNotSet: "설정 안 됨",
      safetyReminder: "안전 알림",
      safetyReminderValue: "목이 아프면 멈추세요",
      language: "언어",
      audio: "오디오",
      audioValue: "실제 로컬 녹음",
      analyzeAudioFile: "오디오 파일 분석",
      analyzeAudioFileValue: "공명 분석기로 파일 보내기",
      analyzeAudioTitle: "분석 결과",
      analyzeAudioFailedTitle: "분석 실패",
      analyzeAudioFailedBody:
        "분석 서버를 켠 뒤 오디오 파일로 다시 시도하세요.",
      analysisCompatibilityFallback:
        "서버가 resonance_vowel을 거부해서 mmm_resonance로 다시 보냈습니다.",
      waitingForAnalysis:
        "서버 분석을 기다리는 중입니다. 곧 한 가지 힌트를 보여드립니다.",
      localFallbackUsed:
        "서버에 연결할 수 없어 기기 내 기본 피드백을 사용했습니다.",
      retryAnalysisTitle: "재시도 분석 결과",
      firstAnalysisTitle: "첫 테이크 분석 결과",
      deleteAccount: "계정 삭제",
    },
  },
} as const;

type WidenStrings<T> = T extends string
  ? string
  : T extends object
    ? { [K in keyof T]: WidenStrings<T[K]> }
    : T;
type MainAppText = WidenStrings<typeof baseMainAppText.en>;
type ExtraMainLanguage = Exclude<MainAppLanguage, "en" | "ko">;

const mainTextTranslations: Record<
  ExtraMainLanguage,
  Record<string, string>
> = {
  es: {
    Today: "Hoy",
    Journey: "Ruta",
    Journal: "Diario",
    Settings: "Ajustes",
    Day: "Día",
    of: "de",
    Week: "Semana",
    "Loading your Rehear journey...": "Cargando tu ruta de Rehear...",
    grace: "gracia",
    Ready: "Listo",
    Used: "Usado",
    today: "hoy",
    streak: "racha",
    "day streak": "racha de días",
    "grace day": "día de gracia",
    "first take": "primera toma",
    retry: "reintento",
    "Training session": "Sesión de práctica",
    "Small honest repetitions are how the voice changes. Today, record once, improve one thing, then retry the exact same drill.":
      "La voz cambia con repeticiones pequeñas y honestas. Hoy graba una vez, mejora una cosa y repite exactamente el mismo ejercicio.",
    "Warm-up": "Calentamiento",
    "Main drill": "Ejercicio principal",
    "Retry rule": "Regla de reintento",
    "Same task, one cue, one comparison.":
      "Misma tarea, una pista, una comparación.",
    "Start recording": "Empezar a grabar",
    "Record the first take.": "Graba la primera toma.",
    "Rehear stores this take locally for the retry comparison.":
      "Rehear guarda esta toma en el dispositivo para compararla con el reintento.",
    "Ready to record": "Listo para grabar",
    "Start first take": "Empezar primera toma",
    "Stop first take": "Detener primera toma",
    "One thing to try.": "Una cosa para probar.",
    "What we heard": "Lo que escuchamos",
    "What it often means": "Lo que suele significar",
    "One fix": "Un ajuste",
    "Retry same drill": "Reintentar el mismo ejercicio",
    "Retry, unchanged.": "Reintento, sin cambios.",
    "Same drill. Same target. Only the cue changes.":
      "Mismo ejercicio. Mismo objetivo. Solo cambia la pista.",
    "Second take comparison": "Comparación de segunda toma",
    "Ready to retry": "Listo para reintentar",
    "Start retry": "Empezar reintento",
    "Stop retry": "Detener reintento",
    "Day complete.": "Día completo.",
    "The app saved this comparison to Journal.":
      "La app guardó esta comparación en el Diario.",
    "Recorded takes": "Tomas grabadas",
    "Back to Today": "Volver a Hoy",
    "Today’s session": "Sesión de hoy",
    "Record, get one cue, retry.": "Graba, recibe una pista y reintenta.",
    "Practice again": "Practicar de nuevo",
    "Start training": "Empezar práctica",
    "Microphone unavailable": "Micrófono no disponible",
    "Allow microphone access to record real takes.":
      "Permite acceso al micrófono para grabar tomas reales.",
    "Microphone setup failed. You can still review the flow, but real recording is unavailable.":
      "Falló la configuración del micrófono. Puedes revisar el flujo, pero no grabar audio real.",
    "Recording could not start. Check mic permission and try again.":
      "No se pudo iniciar la grabación. Revisa el permiso del micrófono e inténtalo otra vez.",
    "Recording could not be saved. Try again with a shorter take.":
      "No se pudo guardar la grabación. Intenta una toma más corta.",
    "Onboarding recommended this starting point inside the roadmap.":
      "El onboarding recomendó este punto de partida dentro de la ruta.",
    "3-month roadmap": "Ruta de 3 meses",
    "Your fixed Rehear journey.": "Tu ruta fija de Rehear.",
    "Onboarding chooses your starting point. The 12-week path stays visible, reviewable, and skippable by checkpoint.":
      "El onboarding elige tu punto de partida. La ruta de 12 semanas queda visible, revisable y saltable por checkpoint.",
    "Current placement": "Ubicación actual",
    "Complete onboarding to place yourself in the curriculum.":
      "Completa el onboarding para ubicarte en el currículo.",
    Review: "Repasar",
    Current: "Actual",
    Locked: "Bloqueado",
    "Skip-ahead checks are shown as prototype affordances. In production, they require one recording, one retry, and no pain report.":
      "Los saltos se muestran como funciones de prototipo. En producción requieren una grabación, un reintento y confirmar que no hay dolor.",
    "Proof against your last take.": "Prueba contra tu última toma.",
    "Rehear saves local take comparisons, not a pile of raw recordings. Each entry keeps the first take, retry, and one written observation.":
      "Rehear guarda comparaciones locales, no una pila de grabaciones. Cada entrada conserva la primera toma, el reintento y una observación escrita.",
    "No saved comparisons yet.": "Aún no hay comparaciones guardadas.",
    "Complete today’s training loop to save the first take, retry result, and one written observation.":
      "Completa el ciclo de hoy para guardar la primera toma, el reintento y una observación.",
    "Latest comparison": "Comparación más reciente",
    "First take": "Primera toma",
    Retry: "Reintento",
    First: "Primera",
    "saved locally": "guardado localmente",
    "no URI": "sin URI",
    "Monthly checkpoints": "Checkpoints mensuales",
    "Month 1 breath and resonance": "Mes 1 respiración y resonancia",
    "Month 2 vocal control": "Mes 2 control vocal",
    "Month 3 final song comparison": "Mes 3 comparación final de canción",
    Open: "Abierto",
    Later: "Más tarde",
    "Keep the promise realistic.": "Mantén realista la promesa.",
    "These controls tune habit pressure without changing the fixed curriculum.":
      "Estos controles ajustan la presión del hábito sin cambiar el currículo fijo.",
    "Daily training": "Práctica diaria",
    "Reminder time": "Hora del recordatorio",
    "Notification tone": "Tono de notificación",
    "Session length": "Duración de sesión",
    "Habit rules": "Reglas del hábito",
    "One missed day per calendar month can use a grace day. The streak survives; the 90-day journey never resets.":
      "Un día perdido por mes puede usar un día de gracia. La racha sobrevive; la ruta de 90 días no se reinicia.",
    "current streak": "racha actual",
    "best streak": "mejor racha",
    Other: "Otros",
    Permissions: "Permisos",
    Notifications: "Notificaciones",
    Microphone: "Micrófono",
    Allowed: "Permitido",
    Denied: "Denegado",
    "Not set": "Sin configurar",
    "Safety reminder": "Recordatorio de seguridad",
    "Stop if your throat hurts": "Detente si te duele la garganta",
    Language: "Idioma",
    Audio: "Audio",
    "Real local recording": "Grabación local real",
    "Analyze audio file": "Analizar archivo de audio",
    "Send file to resonance analyzer":
      "Enviar archivo al analizador de resonancia",
    "Analysis result": "Resultado del análisis",
    "Analysis failed": "Análisis fallido",
    "Start the analysis server and try again with an audio file.":
      "Inicia el servidor de análisis e inténtalo de nuevo con un archivo de audio.",
    "Server rejected resonance_vowel, so Rehear retried with mmm_resonance.":
      "El servidor rechazó resonance_vowel, así que Rehear reintentó con mmm_resonance.",
    "Waiting for server analysis. One cue will appear shortly.":
      "Esperando el análisis del servidor. Pronto aparecerá una pista.",
    "Server unavailable, so Rehear used the local fallback.":
      "El servidor no está disponible, así que Rehear usó la alternativa local.",
    "Retry analysis result": "Resultado del análisis del reintento",
    "First take analysis result": "Resultado del análisis de la primera toma",
    "Delete account": "Eliminar cuenta",
    Analyzing: "Analizando",
    "Reviewing your take…": "Revisando tu toma…",
    "Analysis unavailable": "Análisis no disponible",
    "We could not analyze this take right now. Retry or tap Done to continue.":
      "No pudimos analizar esta toma ahora. Reintenta o pulsa Hecho para continuar.",
    Done: "Hecho",
    "For You": "Para ti",
    "Personalized picks for your singing goal":
      "Selecciones personalizadas para tu objetivo vocal",
    "Show daily goal": "Ver objetivo diario",
    "Daily Goal": "Objetivo diario",
    Exercises: "Ejercicios",
    "Week {number}": "Semana {number}",
    "Show {title}": "Ver {title}",
    "Start {title}": "Empezar {title}",
    "{title} exercise illustration": "Ilustración del ejercicio {title}",
    "Analyzing take": "Analizando toma",
    Goal: "Objetivo",
    Instructions: "Instrucciones",
    Start: "Empezar",
    Set: "Preparado",
    Go: "Ya",
    Back: "Atrás",
    Close: "Cerrar",
    "Coming soon": "Próximamente",
    "We will open this month after the Month 1 practice and analysis engine is complete.":
      "Abriremos este mes cuando terminemos la práctica del Mes 1 y el motor de análisis.",
    "For now, only Month 1 breath and resonance training is available.":
      "Por ahora solo está disponible el entrenamiento de respiración y resonancia del Mes 1.",
    "Success check": "Criterio de éxito",
    "What you'll practice": "Lo que practicarás",
    Focus: "Enfoque",
    How: "Cómo",
    "Your schedule": "Tu horario",
    "Practice the same exercises every day this week.":
      "Practica los mismos ejercicios cada día esta semana.",
    "Safety rules": "Reglas de seguridad",
    "You're on {day}": "Estás en {day}",
    "Opens this week's goal and training":
      "Abre el objetivo y entrenamiento de esta semana",
    Next: "Siguiente",
    "Month {month} testing center": "Centro de pruebas del mes {month}",
    "Monthly checkpoint": "Checkpoint mensual",
    "Monthly checkpoint · passed": "Checkpoint mensual · aprobado",
    "The testing center needs real recording permission.":
      "El centro de pruebas necesita permiso de grabación real.",
    "Recording could not start": "No se pudo iniciar la grabación",
    "Please try again.": "Inténtalo de nuevo.",
    "Could not reach the analysis server. Try again.":
      "No se pudo conectar al servidor de análisis. Inténtalo de nuevo.",
    "Month-end gate": "Control de fin de mes",
    "Record and analyze each check to confirm Month 1 foundations are stable.":
      "Graba y analiza cada prueba para confirmar que las bases del Mes 1 son estables.",
    "This testing center is opening soon.":
      "Este centro de pruebas abrirá pronto.",
    Progress: "Progreso",
    "Already passed": "Ya aprobado",
    "Month 1 test passed": "Prueba del Mes 1 aprobada",
    "You are ready to open the next month.":
      "Estás listo para abrir el mes siguiente.",
    "Only Month 1 testing is available right now.":
      "Solo están disponibles las pruebas del Mes 1.",
    "The recording quality was not enough. Record a clearer take.":
      "La calidad de la grabación no fue suficiente. Graba una toma más clara.",
    "Passed. Move to the next check.":
      "Aprobado. Pasa a la siguiente prueba.",
    Passed: "Aprobado",
    Waiting: "Esperando",
    "Stop recording": "Detener grabación",
    "Record again": "Grabar de nuevo",
  },
  pt: {},
  fr: {},
  de: {},
  ja: {},
  zhHans: {},
  zhHant: {},
  hi: {},
  ar: {},
  id: {},
};

function localizeMainTree<T>(value: T, language: ExtraMainLanguage): T {
  if (typeof value === "string") {
    const translated =
      mainTextTranslations[language][value] ?? mainTextTranslations.es[value];
    return (translated ?? value) as T;
  }

  if (Array.isArray(value)) {
    return value.map((item) => localizeMainTree(item, language)) as T;
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [
        key,
        localizeMainTree(item, language),
      ]),
    ) as T;
  }

  return value;
}

type CompactMainPack = {
  tabs: [string, string, string, string];
  common: [
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
  ];
  today: string[];
  journey: string[];
  journal: string[];
  settings: string[];
};

function mergeMainText(
  localized: Partial<MainAppText>,
  fallback: MainAppText = baseMainAppText.en,
): MainAppText {
  return Object.fromEntries(
    (Object.keys(fallback) as (keyof MainAppText)[]).map((section) => {
      const localizedSection = localized[section];
      const fallbackSection = fallback[section];

      if (
        localizedSection &&
        typeof localizedSection === "object" &&
        fallbackSection &&
        typeof fallbackSection === "object"
      ) {
        return [
          section,
          {
            ...fallbackSection,
            ...(localizedSection as Record<string, string>),
          },
        ];
      }

      return [section, fallbackSection];
    }),
  ) as MainAppText;
}

export function fillTemplate(
  template: string,
  values: Record<string, string | number>,
) {
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    template,
  );
}

const compactMainPacks: Record<
  Exclude<ExtraMainLanguage, "es">,
  CompactMainPack
> = {
  pt: {
    tabs: ["Hoje", "Jornada", "Diário", "Configurações"],
    common: [
      "Dia",
      "de",
      "Semana",
      "Carregando sua jornada Rehear...",
      "folga",
      "Pronto",
      "Usado",
      "hoje",
      "sequência",
      "dias seguidos",
      "dia de folga",
      "primeira tomada",
      "repetição",
    ],
    today: [
      "Sessão de treino",
      "Pequenas repetições honestas mudam a voz. Hoje, grave uma vez, ajuste uma coisa e repita o mesmo exercício.",
      "Aquecimento",
      "Exercício principal",
      "Regra de repetição",
      "Mesma tarefa, uma dica, uma comparação.",
      "Começar gravação",
      "Grave a primeira tomada.",
      "Rehear salva esta tomada no aparelho para comparar com a repetição.",
      "Pronto para gravar",
      "Iniciar primeira tomada",
      "Parar primeira tomada",
      "Uma coisa para tentar.",
      "O que ouvimos",
      "O que isso costuma significar",
      "Um ajuste",
      "Repetir o mesmo exercício",
      "Repita sem mudar.",
      "Mesmo exercício. Mesmo alvo. Só a dica muda.",
      "Comparação da segunda tomada",
      "Pronto para repetir",
      "Iniciar repetição",
      "Parar repetição",
      "Dia completo.",
      "A comparação foi salva no Diário.",
      "Tomadas gravadas",
      "Voltar para Hoje",
      "Sessão de hoje",
      "Grave, receba uma dica e repita.",
      "Praticar de novo",
      "Começar treino",
      "Microfone indisponível",
      "Permita acesso ao microfone para gravar tomadas reais.",
      "Falha ao configurar o microfone. Você ainda pode ver o fluxo, mas a gravação real não está disponível.",
      "Não foi possível iniciar a gravação. Verifique a permissão do microfone e tente novamente.",
      "Não foi possível salvar a gravação. Tente uma tomada mais curta.",
      "O onboarding recomendou este ponto de partida dentro do roteiro fixo.",
    ],
    journey: [
      "Roteiro de 3 meses",
      "Sua jornada fixa Rehear.",
      "O onboarding escolhe seu ponto inicial. O caminho de 12 semanas fica visível, revisável e avançável por checkpoint.",
      "Posição atual",
      "Conclua o onboarding para se posicionar no currículo.",
      "Revisar",
      "Atual",
      "Bloqueado",
      "Os avanços aparecem como recurso de protótipo. Em produção, exigem uma gravação, uma repetição e ausência de dor.",
    ],
    journal: [
      "Diário",
      "Prova contra sua última tomada.",
      "Rehear salva comparações locais de tomadas, não uma pilha de gravações brutas. Cada entrada guarda primeira tomada, repetição e uma observação.",
      "Nenhuma comparação salva ainda.",
      "Complete o treino de hoje para salvar primeira tomada, repetição e observação.",
      "Comparação mais recente",
      "Primeira tomada",
      "Repetição",
      "Primeira",
      "salvo localmente",
      "sem URI",
      "Checkpoints mensais",
      "Mês 1 respiração e ressonância",
      "Mês 2 controle vocal",
      "Mês 3 comparação final da música",
      "Aberto",
      "Depois",
    ],
    settings: [
      "Configurações",
      "Mantenha a promessa realista.",
      "Estes controles ajustam a pressão do hábito sem mudar o currículo fixo.",
      "Treino diário",
      "Horário do lembrete",
      "Tom da notificação",
      "Duração da sessão",
      "Regras do hábito",
      "Um dia perdido por mês pode usar um dia de folga. A sequência sobrevive; a jornada de 90 dias não reinicia.",
      "sequência atual",
      "melhor sequência",
      "Outros",
      "Lembrete de segurança",
      "Pare se a garganta doer",
      "Idioma",
      "Áudio",
      "Gravação local real",
      "Analisar arquivo de áudio",
      "Enviar arquivo ao analisador de ressonância",
      "Resultado da análise",
      "Falha na análise",
      "Inicie o servidor de análise e tente novamente com um arquivo de áudio.",
      "O servidor rejeitou resonance_vowel; Rehear tentou novamente com mmm_resonance.",
      "Aguardando análise do servidor. Uma dica aparecerá em breve.",
      "Servidor indisponível, então Rehear usou o fallback local.",
      "Resultado da repetição",
      "Resultado da primeira tomada",
      "Excluir conta",
      "Permissões",
      "Notificações",
      "Microfone",
      "Permitido",
      "Negado",
      "Não definido",
    ],
  },
  fr: {
    tabs: ["Aujourd’hui", "Parcours", "Journal", "Réglages"],
    common: [
      "Jour",
      "sur",
      "Semaine",
      "Chargement de votre parcours Rehear...",
      "joker",
      "Prêt",
      "Utilisé",
      "aujourd’hui",
      "série",
      "jours de série",
      "jour joker",
      "première prise",
      "reprise",
    ],
    today: [
      "Séance d’entraînement",
      "La voix change par petites répétitions honnêtes. Aujourd’hui, enregistrez une fois, améliorez une chose, puis refaites le même exercice.",
      "Échauffement",
      "Exercice principal",
      "Règle de reprise",
      "Même tâche, un conseil, une comparaison.",
      "Commencer l’enregistrement",
      "Enregistrez la première prise.",
      "Rehear garde cette prise sur l’appareil pour la comparaison.",
      "Prêt à enregistrer",
      "Démarrer première prise",
      "Arrêter première prise",
      "Une chose à essayer.",
      "Ce que nous avons entendu",
      "Ce que cela signifie souvent",
      "Un ajustement",
      "Refaire le même exercice",
      "Reprise sans changement.",
      "Même exercice. Même cible. Seul le conseil change.",
      "Comparaison de la deuxième prise",
      "Prêt pour la reprise",
      "Démarrer la reprise",
      "Arrêter la reprise",
      "Jour terminé.",
      "La comparaison a été enregistrée dans le Journal.",
      "Prises enregistrées",
      "Retour à Aujourd’hui",
      "Séance du jour",
      "Enregistrez, recevez un conseil, recommencez.",
      "Pratiquer encore",
      "Commencer",
      "Micro indisponible",
      "Autorisez le micro pour enregistrer de vraies prises.",
      "Échec de configuration du micro. Le flux reste visible, mais l’enregistrement réel est indisponible.",
      "Impossible de démarrer l’enregistrement. Vérifiez l’autorisation micro et réessayez.",
      "Impossible de sauvegarder. Essayez une prise plus courte.",
      "L’onboarding a recommandé ce point de départ dans le parcours fixe.",
    ],
    journey: [
      "Parcours de 3 mois",
      "Votre parcours Rehear fixe.",
      "L’onboarding choisit votre point de départ. Le chemin de 12 semaines reste visible, révisable et franchissable par checkpoint.",
      "Position actuelle",
      "Terminez l’onboarding pour vous placer dans le programme.",
      "Revoir",
      "Actuel",
      "Verrouillé",
      "Les sauts sont montrés comme fonctions de prototype. En production, ils demandent un enregistrement, une reprise et aucun signal de douleur.",
    ],
    journal: [
      "Journal",
      "Preuve face à votre dernière prise.",
      "Rehear sauvegarde des comparaisons locales, pas une pile d’audios bruts. Chaque entrée garde première prise, reprise et observation.",
      "Aucune comparaison sauvegardée.",
      "Terminez la boucle du jour pour sauvegarder première prise, reprise et observation.",
      "Dernière comparaison",
      "Première prise",
      "Reprise",
      "Première",
      "sauvegardé localement",
      "aucune URI",
      "Checkpoints mensuels",
      "Mois 1 souffle et résonance",
      "Mois 2 contrôle vocal",
      "Mois 3 comparaison finale de chanson",
      "Ouvert",
      "Plus tard",
    ],
    settings: [
      "Réglages",
      "Gardez la promesse réaliste.",
      "Ces contrôles règlent la pression d’habitude sans changer le programme fixe.",
      "Entraînement quotidien",
      "Heure du rappel",
      "Ton de notification",
      "Durée de séance",
      "Règles d’habitude",
      "Un jour manqué par mois peut utiliser un jour joker. La série survit ; le parcours de 90 jours ne redémarre pas.",
      "série actuelle",
      "meilleure série",
      "Autre",
      "Rappel sécurité",
      "Arrêtez si la gorge fait mal",
      "Langue",
      "Audio",
      "Enregistrement local réel",
      "Analyser un fichier audio",
      "Envoyer au détecteur de résonance",
      "Résultat d’analyse",
      "Échec d’analyse",
      "Lancez le serveur d’analyse et réessayez avec un fichier audio.",
      "Le serveur a refusé resonance_vowel ; Rehear a réessayé avec mmm_resonance.",
      "Analyse serveur en attente. Un conseil apparaîtra bientôt.",
      "Serveur indisponible, Rehear utilise le fallback local.",
      "Résultat de reprise",
      "Résultat de première prise",
      "Supprimer le compte",
      "Autorisations",
      "Notifications",
      "Microphone",
      "Autorisé",
      "Refusé",
      "Non défini",
    ],
  },
  de: {
    tabs: ["Heute", "Reise", "Journal", "Einstellungen"],
    common: [
      "Tag",
      "von",
      "Woche",
      "Rehear-Reise wird geladen...",
      "Gnade",
      "Bereit",
      "Genutzt",
      "heute",
      "Serie",
      "Tage-Serie",
      "Gnadentag",
      "erster Take",
      "Retry",
    ],
    today: [
      "Trainingseinheit",
      "Kleine ehrliche Wiederholungen verändern die Stimme. Nimm heute einmal auf, verbessere eine Sache und wiederhole dieselbe Übung.",
      "Aufwärmen",
      "Hauptübung",
      "Retry-Regel",
      "Gleiche Aufgabe, ein Hinweis, ein Vergleich.",
      "Aufnahme starten",
      "Nimm den ersten Take auf.",
      "Rehear speichert diesen Take lokal für den Vergleich.",
      "Bereit zur Aufnahme",
      "Ersten Take starten",
      "Ersten Take stoppen",
      "Eine Sache zum Probieren.",
      "Was wir gehört haben",
      "Was es oft bedeutet",
      "Eine Korrektur",
      "Gleiche Übung wiederholen",
      "Retry unverändert.",
      "Gleiche Übung. Gleiches Ziel. Nur der Hinweis ändert sich.",
      "Vergleich zweiter Take",
      "Bereit für Retry",
      "Retry starten",
      "Retry stoppen",
      "Tag abgeschlossen.",
      "Der Vergleich wurde im Journal gespeichert.",
      "Aufgenommene Takes",
      "Zurück zu Heute",
      "Heutige Einheit",
      "Aufnehmen, Hinweis bekommen, wiederholen.",
      "Noch einmal üben",
      "Training starten",
      "Mikrofon nicht verfügbar",
      "Erlaube Mikrofonzugriff für echte Takes.",
      "Mikrofon-Setup fehlgeschlagen. Der Ablauf bleibt sichtbar, echte Aufnahme ist nicht verfügbar.",
      "Aufnahme konnte nicht starten. Prüfe die Mikrofonberechtigung.",
      "Aufnahme konnte nicht gespeichert werden. Versuche einen kürzeren Take.",
      "Das Onboarding empfiehlt diesen Startpunkt im festen Plan.",
    ],
    journey: [
      "3-Monats-Plan",
      "Deine feste Rehear-Reise.",
      "Das Onboarding wählt deinen Startpunkt. Der 12-Wochen-Pfad bleibt sichtbar, prüfbar und per Checkpoint überspringbar.",
      "Aktuelle Position",
      "Schließe das Onboarding ab, um dich im Curriculum zu platzieren.",
      "Prüfen",
      "Aktuell",
      "Gesperrt",
      "Überspringen wird als Prototyp-Funktion gezeigt. In Produktion braucht es eine Aufnahme, einen Retry und keine Schmerzmeldung.",
    ],
    journal: [
      "Journal",
      "Beweis gegenüber deinem letzten Take.",
      "Rehear speichert lokale Take-Vergleiche statt roher Aufnahmeberge. Jeder Eintrag enthält ersten Take, Retry und Beobachtung.",
      "Noch keine Vergleiche gespeichert.",
      "Schließe den heutigen Trainingsloop ab, um Take, Retry und Beobachtung zu speichern.",
      "Neuester Vergleich",
      "Erster Take",
      "Retry",
      "Erster",
      "lokal gespeichert",
      "keine URI",
      "Monatliche Checkpoints",
      "Monat 1 Atem und Resonanz",
      "Monat 2 Stimmkontrolle",
      "Monat 3 finaler Songvergleich",
      "Offen",
      "Später",
    ],
    settings: [
      "Einstellungen",
      "Halte das Versprechen realistisch.",
      "Diese Steuerungen ändern den Gewohnheitsdruck, nicht das feste Curriculum.",
      "Tägliches Training",
      "Erinnerungszeit",
      "Benachrichtigungston",
      "Sitzungslänge",
      "Gewohnheitsregeln",
      "Ein verpasster Tag pro Monat kann ein Gnadentag sein. Die Serie bleibt, die 90-Tage-Reise startet nicht neu.",
      "aktuelle Serie",
      "beste Serie",
      "Sonstiges",
      "Sicherheits-Erinnerung",
      "Stoppe, wenn der Hals weh tut",
      "Sprache",
      "Audio",
      "Echte lokale Aufnahme",
      "Audiodatei analysieren",
      "Datei an Resonanzanalyse senden",
      "Analyseergebnis",
      "Analyse fehlgeschlagen",
      "Starte den Analyseserver und versuche es mit einer Audiodatei erneut.",
      "Server lehnte resonance_vowel ab; Rehear versuchte mmm_resonance.",
      "Warte auf Serveranalyse. Ein Hinweis erscheint gleich.",
      "Server nicht verfügbar, Rehear nutzt lokalen Fallback.",
      "Retry-Analyseergebnis",
      "Analyseergebnis erster Take",
      "Konto löschen",
      "Berechtigungen",
      "Benachrichtigungen",
      "Mikrofon",
      "Erlaubt",
      "Verweigert",
      "Nicht festgelegt",
    ],
  },
  ja: {
    tabs: ["今日", "旅程", "ジャーナル", "設定"],
    common: [
      "日目",
      "/",
      "週",
      "Rehear の旅程を読み込み中...",
      "猶予",
      "準備完了",
      "使用済み",
      "今日",
      "連続",
      "連続日数",
      "猶予日",
      "最初のテイク",
      "リトライ",
    ],
    today: [
      "トレーニングセッション",
      "声は小さな正直な反復で変わります。今日は一度録音し、一つだけ直して、同じドリルをもう一度行います。",
      "ウォームアップ",
      "メインドリル",
      "リトライ規則",
      "同じ課題、一つのヒント、一つの比較。",
      "録音開始",
      "最初のテイクを録音します。",
      "Rehear はリトライ比較のため、このテイクを端末に保存します。",
      "録音準備完了",
      "最初のテイク開始",
      "最初のテイク停止",
      "試すことを一つ。",
      "聞こえたこと",
      "よくある意味",
      "一つの修正",
      "同じドリルをリトライ",
      "変えずにリトライ。",
      "同じドリル。同じ目標。変わるのはヒントだけです。",
      "2回目テイク比較",
      "リトライ準備完了",
      "リトライ開始",
      "リトライ停止",
      "今日の練習完了。",
      "比較をジャーナルに保存しました。",
      "録音したテイク",
      "今日へ戻る",
      "今日のセッション",
      "録音し、ヒントを受け取り、リトライ。",
      "もう一度練習",
      "トレーニング開始",
      "マイクが使えません",
      "実際のテイク録音にはマイクアクセスを許可してください。",
      "マイク設定に失敗しました。流れは確認できますが実録音は使えません。",
      "録音を開始できません。マイク権限を確認してください。",
      "録音を保存できません。短いテイクで再試行してください。",
      "オンボーディングが固定ロードマップ内の開始点を推奨しました。",
    ],
    journey: [
      "3か月ロードマップ",
      "固定された Rehear の旅程。",
      "オンボーディングが開始点を選びます。12週の道のりは表示され、確認でき、チェックポイントで進めます。",
      "現在の位置",
      "オンボーディングを完了するとカリキュラム上の位置が決まります。",
      "復習",
      "現在",
      "ロック中",
      "先へのチェックはプロトタイプ機能です。本番では録音1回、リトライ1回、痛みなしの確認が必要です。",
    ],
    journal: [
      "ジャーナル",
      "前回テイクとの証拠。",
      "Rehear は生録音の山ではなく、ローカルのテイク比較を保存します。各項目に最初のテイク、リトライ、観察を残します。",
      "保存された比較はまだありません。",
      "今日の練習ループを完了すると、最初のテイク、リトライ、観察が保存されます。",
      "最新の比較",
      "最初のテイク",
      "リトライ",
      "最初",
      "端末に保存済み",
      "URI なし",
      "月次チェックポイント",
      "1か月目 息と響き",
      "2か月目 声のコントロール",
      "3か月目 最終曲比較",
      "開く",
      "あとで",
    ],
    settings: [
      "設定",
      "約束を現実的に保つ。",
      "これらの設定は固定カリキュラムを変えず、習慣の負荷だけ調整します。",
      "毎日の練習",
      "リマインダー時刻",
      "通知トーン",
      "セッション時間",
      "習慣ルール",
      "月に1日は猶予日として使えます。連続記録は残り、90日の旅程はリセットされません。",
      "現在の連続日数",
      "最高連続日数",
      "その他",
      "安全リマインダー",
      "喉が痛ければ止める",
      "言語",
      "オーディオ",
      "実際のローカル録音",
      "音声ファイルを分析",
      "共鳴分析へ送信",
      "分析結果",
      "分析失敗",
      "分析サーバーを起動し、音声ファイルで再試行してください。",
      "サーバーが resonance_vowel を拒否したため mmm_resonance で再送しました。",
      "サーバー分析を待っています。まもなくヒントが表示されます。",
      "サーバーが使えないためローカルの代替フィードバックを使用しました。",
      "リトライ分析結果",
      "最初のテイク分析結果",
      "アカウントを削除",
      "権限",
      "通知",
      "マイク",
      "許可",
      "拒否",
      "未設定",
    ],
  },
  zhHans: {
    tabs: ["今天", "旅程", "日志", "设置"],
    common: [
      "第",
      "/",
      "周",
      "正在加载 Rehear 旅程...",
      "宽限",
      "准备好",
      "已用",
      "今天",
      "连续",
      "连续天数",
      "宽限日",
      "第一条录音",
      "重试",
    ],
    today: [
      "训练课",
      "声音靠小而真实的重复改变。今天录一次，改进一件事，再做同一个练习。",
      "热身",
      "主要练习",
      "重试规则",
      "同一任务，一个提示，一次比较。",
      "开始录音",
      "录下第一条。",
      "Rehear 会在本机保存这条录音用于重试比较。",
      "准备录音",
      "开始第一条",
      "停止第一条",
      "尝试一件事。",
      "我们听到",
      "通常意味着",
      "一个修正",
      "重试同一练习",
      "不改变，重试。",
      "同一练习。同一目标。只改变提示。",
      "第二条比较",
      "准备重试",
      "开始重试",
      "停止重试",
      "今天完成。",
      "比较已保存到日志。",
      "已录音",
      "回到今天",
      "今天的课程",
      "录音，得到一个提示，再重试。",
      "再次练习",
      "开始训练",
      "麦克风不可用",
      "允许麦克风以录制真实录音。",
      "麦克风设置失败。仍可查看流程，但无法真实录音。",
      "无法开始录音。请检查麦克风权限后重试。",
      "无法保存录音。请尝试更短的录音。",
      "引导流程推荐了固定路线中的这个起点。",
    ],
    journey: [
      "3个月路线图",
      "你的固定 Rehear 旅程。",
      "引导流程选择起点。12周路径保持可见、可复习，并可按检查点前进。",
      "当前位置",
      "完成引导后进入课程位置。",
      "复习",
      "当前",
      "锁定",
      "跳级检查是原型功能。正式版需要一次录音、一次重试，并确认无疼痛。",
    ],
    journal: [
      "日志",
      "与你上一条录音对照的证据。",
      "Rehear 保存本机录音比较，而不是一堆原始录音。每条包含第一条、重试和一个观察。",
      "还没有保存的比较。",
      "完成今天训练后会保存第一条、重试和观察。",
      "最新比较",
      "第一条",
      "重试",
      "第一条",
      "本机已保存",
      "无 URI",
      "月度检查点",
      "第1月 气息与共鸣",
      "第2月 声音控制",
      "第3月 最终歌曲比较",
      "打开",
      "稍后",
    ],
    settings: [
      "设置",
      "让承诺保持现实。",
      "这些控制只调整习惯压力，不改变固定课程。",
      "每日训练",
      "提醒时间",
      "通知语气",
      "课程时长",
      "习惯规则",
      "每月可用一天宽限日。连续记录保留；90天旅程不会重置。",
      "当前连续",
      "最佳连续",
      "其他",
      "安全提醒",
      "喉咙痛就停止",
      "语言",
      "音频",
      "真实本机录音",
      "分析音频文件",
      "发送到共鸣分析器",
      "分析结果",
      "分析失败",
      "启动分析服务器并用音频文件重试。",
      "服务器拒绝 resonance_vowel，Rehear 已用 mmm_resonance 重试。",
      "等待服务器分析。很快会显示一个提示。",
      "服务器不可用，因此 Rehear 使用本机备用反馈。",
      "重试分析结果",
      "第一条分析结果",
      "删除账户",
      "权限",
      "通知",
      "麦克风",
      "已允许",
      "已拒绝",
      "未设置",
    ],
  },
  zhHant: {
    tabs: ["今天", "旅程", "日誌", "設定"],
    common: [
      "第",
      "/",
      "週",
      "正在載入 Rehear 旅程...",
      "寬限",
      "準備好",
      "已用",
      "今天",
      "連續",
      "連續天數",
      "寬限日",
      "第一條錄音",
      "重試",
    ],
    today: [
      "訓練課",
      "聲音靠小而真實的重複改變。今天錄一次，改進一件事，再做同一個練習。",
      "熱身",
      "主要練習",
      "重試規則",
      "同一任務，一個提示，一次比較。",
      "開始錄音",
      "錄下第一條。",
      "Rehear 會在本機保存這條錄音用於重試比較。",
      "準備錄音",
      "開始第一條",
      "停止第一條",
      "嘗試一件事。",
      "我們聽到",
      "通常意味著",
      "一個修正",
      "重試同一練習",
      "不改變，重試。",
      "同一練習。同一目標。只改變提示。",
      "第二條比較",
      "準備重試",
      "開始重試",
      "停止重試",
      "今天完成。",
      "比較已保存到日誌。",
      "已錄音",
      "回到今天",
      "今天的課程",
      "錄音，得到一個提示，再重試。",
      "再次練習",
      "開始訓練",
      "麥克風不可用",
      "允許麥克風以錄製真實錄音。",
      "麥克風設定失敗。仍可查看流程，但無法真實錄音。",
      "無法開始錄音。請檢查麥克風權限後重試。",
      "無法保存錄音。請嘗試更短的錄音。",
      "引導流程推薦了固定路線中的這個起點。",
    ],
    journey: [
      "3個月路線圖",
      "你的固定 Rehear 旅程。",
      "引導流程選擇起點。12週路徑保持可見、可複習，並可按檢查點前進。",
      "目前位置",
      "完成引導後進入課程位置。",
      "複習",
      "目前",
      "鎖定",
      "跳級檢查是原型功能。正式版需要一次錄音、一次重試，並確認無疼痛。",
    ],
    journal: [
      "日誌",
      "與你上一條錄音對照的證據。",
      "Rehear 保存本機錄音比較，而不是一堆原始錄音。每條包含第一條、重試和一個觀察。",
      "還沒有保存的比較。",
      "完成今天訓練後會保存第一條、重試和觀察。",
      "最新比較",
      "第一條",
      "重試",
      "第一條",
      "本機已保存",
      "無 URI",
      "月度檢查點",
      "第1月 氣息與共鳴",
      "第2月 声音控制",
      "第3月 最終歌曲比較",
      "打開",
      "稍後",
    ],
    settings: [
      "設定",
      "讓承諾保持現實。",
      "這些控制只調整習慣壓力，不改變固定課程。",
      "每日訓練",
      "提醒時間",
      "通知語氣",
      "課程時長",
      "習慣規則",
      "每月可用一天寬限日。連續記錄保留；90天旅程不會重置。",
      "目前連續",
      "最佳連續",
      "其他",
      "安全提醒",
      "喉嚨痛就停止",
      "語言",
      "音訊",
      "真實本機錄音",
      "分析音訊檔案",
      "發送到共鳴分析器",
      "分析結果",
      "分析失敗",
      "啟動分析伺服器並用音訊檔案重試。",
      "伺服器拒絕 resonance_vowel，Rehear 已用 mmm_resonance 重試。",
      "等待伺服器分析。很快會顯示一個提示。",
      "伺服器不可用，因此 Rehear 使用本機備用回饋。",
      "重試分析結果",
      "第一條分析結果",
      "刪除帳戶",
      "權限",
      "通知",
      "麥克風",
      "已允許",
      "已拒絕",
      "未設定",
    ],
  },
  hi: {
    tabs: ["आज", "यात्रा", "जर्नल", "सेटिंग्स"],
    common: [
      "दिन",
      "में से",
      "सप्ताह",
      "आपकी Rehear यात्रा लोड हो रही है...",
      "ग्रेस",
      "तैयार",
      "उपयोग हुआ",
      "आज",
      "स्ट्रीक",
      "दिन की स्ट्रीक",
      "ग्रेस डे",
      "पहली टेक",
      "दोबारा",
    ],
    today: [
      "ट्रेनिंग सेशन",
      "आवाज छोटे ईमानदार दोहरावों से बदलती है. आज एक बार रिकॉर्ड करें, एक चीज सुधारें, फिर वही अभ्यास दोहराएं.",
      "वार्म-अप",
      "मुख्य अभ्यास",
      "दोहराने का नियम",
      "वही काम, एक संकेत, एक तुलना.",
      "रिकॉर्डिंग शुरू करें",
      "पहली टेक रिकॉर्ड करें.",
      "Rehear इस टेक को तुलना के लिए डिवाइस पर सहेजता है.",
      "रिकॉर्ड करने के लिए तैयार",
      "पहली टेक शुरू करें",
      "पहली टेक रोकें",
      "एक चीज आजमाएं.",
      "हमने क्या सुना",
      "अक्सर इसका मतलब",
      "एक सुधार",
      "वही अभ्यास दोहराएं",
      "बिना बदले दोहराएं.",
      "वही अभ्यास. वही लक्ष्य. केवल संकेत बदलता है.",
      "दूसरी टेक तुलना",
      "दोहराने के लिए तैयार",
      "दोबारा शुरू करें",
      "दोबारा रोकें",
      "दिन पूरा.",
      "तुलना जर्नल में सहेजी गई.",
      "रिकॉर्ड की गई टेक",
      "आज पर लौटें",
      "आज का सेशन",
      "रिकॉर्ड करें, एक संकेत लें, दोहराएं.",
      "फिर अभ्यास करें",
      "ट्रेनिंग शुरू करें",
      "माइक्रोफोन उपलब्ध नहीं",
      "वास्तविक टेक रिकॉर्ड करने के लिए माइक्रोफोन अनुमति दें.",
      "माइक्रोफोन सेटअप विफल. आप प्रवाह देख सकते हैं, पर रिकॉर्डिंग उपलब्ध नहीं.",
      "रिकॉर्डिंग शुरू नहीं हुई. अनुमति जांचें और फिर कोशिश करें.",
      "रिकॉर्डिंग सहेजी नहीं जा सकी. छोटी टेक आजमाएं.",
      "ऑनबोर्डिंग ने तय रोडमैप में यह शुरुआती बिंदु सुझाया.",
    ],
    journey: [
      "3 महीने का रोडमैप",
      "आपकी तय Rehear यात्रा.",
      "ऑनबोर्डिंग आपका शुरुआती बिंदु चुनती है. 12-सप्ताह रास्ता दिखता, समीक्षा योग्य और चेकपॉइंट से आगे बढ़ने योग्य रहता है.",
      "वर्तमान स्थान",
      "कोर्स में अपना स्थान पाने के लिए ऑनबोर्डिंग पूरी करें.",
      "समीक्षा",
      "वर्तमान",
      "लॉक",
      "आगे बढ़ने की जांचें प्रोटोटाइप सुविधा हैं. उत्पादन में एक रिकॉर्डिंग, एक दोबारा प्रयास और दर्द न होने की पुष्टि चाहिए.",
    ],
    journal: [
      "जर्नल",
      "आपकी पिछली टेक के सामने प्रमाण.",
      "Rehear कच्ची रिकॉर्डिंगों की ढेर नहीं, स्थानीय टेक तुलना सहेजता है. हर एंट्री में पहली टेक, दोबारा और एक अवलोकन रहता है.",
      "अभी कोई तुलना सहेजी नहीं.",
      "आज की ट्रेनिंग पूरी करें ताकि पहली टेक, दोबारा परिणाम और अवलोकन सहेजे जाएं.",
      "नवीनतम तुलना",
      "पहली टेक",
      "दोबारा",
      "पहली",
      "स्थानीय रूप से सहेजा",
      "URI नहीं",
      "मासिक चेकपॉइंट",
      "माह 1 सांस और अनुनाद",
      "माह 2 वोकल नियंत्रण",
      "माह 3 अंतिम गीत तुलना",
      "खुला",
      "बाद में",
    ],
    settings: [
      "सेटिंग्स",
      "वादा वास्तविक रखें.",
      "ये नियंत्रण तय कोर्स बदले बिना आदत का दबाव समायोजित करते हैं.",
      "दैनिक ट्रेनिंग",
      "रिमाइंडर समय",
      "नोटिफिकेशन टोन",
      "सेशन लंबाई",
      "आदत नियम",
      "हर महीने एक छूटा दिन ग्रेस डे ले सकता है. स्ट्रीक बचती है; 90-दिन यात्रा रीसेट नहीं होती.",
      "वर्तमान स्ट्रीक",
      "सबसे अच्छी स्ट्रीक",
      "अन्य",
      "सुरक्षा रिमाइंडर",
      "गला दुखे तो रुकें",
      "भाषा",
      "ऑडियो",
      "वास्तविक स्थानीय रिकॉर्डिंग",
      "ऑडियो फाइल विश्लेषण",
      "रेज़ोनेंस एनालाइज़र को भेजें",
      "विश्लेषण परिणाम",
      "विश्लेषण विफल",
      "विश्लेषण सर्वर शुरू करें और ऑडियो फाइल से फिर कोशिश करें.",
      "सर्वर ने resonance_vowel अस्वीकार किया, इसलिए Rehear ने mmm_resonance से दोबारा कोशिश की.",
      "सर्वर विश्लेषण की प्रतीक्षा है. संकेत जल्द दिखेगा.",
      "सर्वर उपलब्ध नहीं, इसलिए Rehear ने स्थानीय fallback उपयोग किया.",
      "दोबारा विश्लेषण परिणाम",
      "पहली टेक विश्लेषण परिणाम",
      "खाता हटाएँ",
      "अनुमतियाँ",
      "सूचनाएँ",
      "माइक्रोफ़ोन",
      "अनुमति है",
      "अस्वीकृत",
      "सेट नहीं",
    ],
  },
  ar: {
    tabs: ["اليوم", "الرحلة", "السجل", "الإعدادات"],
    common: [
      "اليوم",
      "من",
      "الأسبوع",
      "يتم تحميل رحلة Rehear...",
      "سماح",
      "جاهز",
      "مستخدم",
      "اليوم",
      "سلسلة",
      "أيام متتالية",
      "يوم سماح",
      "التسجيل الأول",
      "إعادة",
    ],
    today: [
      "جلسة تدريب",
      "يتغير الصوت بتكرارات صغيرة وصادقة. اليوم سجّل مرة، أصلح شيئا واحدا، ثم أعد التمرين نفسه.",
      "إحماء",
      "التمرين الرئيسي",
      "قاعدة الإعادة",
      "نفس المهمة، تلميح واحد، مقارنة واحدة.",
      "ابدأ التسجيل",
      "سجّل المحاولة الأولى.",
      "يحفظ Rehear هذا التسجيل محليا للمقارنة.",
      "جاهز للتسجيل",
      "ابدأ التسجيل الأول",
      "أوقف التسجيل الأول",
      "شيء واحد للتجربة.",
      "ما سمعناه",
      "ما يعنيه غالبا",
      "إصلاح واحد",
      "أعد التمرين نفسه",
      "أعد دون تغيير.",
      "نفس التمرين. نفس الهدف. يتغير التلميح فقط.",
      "مقارنة التسجيل الثاني",
      "جاهز للإعادة",
      "ابدأ الإعادة",
      "أوقف الإعادة",
      "اكتمل اليوم.",
      "تم حفظ المقارنة في السجل.",
      "التسجيلات المحفوظة",
      "العودة إلى اليوم",
      "جلسة اليوم",
      "سجّل، خذ تلميحا، أعد.",
      "تدرب مرة أخرى",
      "ابدأ التدريب",
      "الميكروفون غير متاح",
      "اسمح بالميكروفون لتسجيل محاولات حقيقية.",
      "فشل إعداد الميكروفون. يمكنك مراجعة التدفق، لكن التسجيل الحقيقي غير متاح.",
      "تعذر بدء التسجيل. تحقق من إذن الميكروفون وحاول ثانية.",
      "تعذر حفظ التسجيل. جرّب تسجيلا أقصر.",
      "أوصى الإعداد بهذا الموضع داخل الخطة الثابتة.",
    ],
    journey: [
      "خارطة 3 أشهر",
      "رحلتك الثابتة في Rehear.",
      "يختار الإعداد نقطة البداية. يبقى مسار 12 أسبوعا مرئيا وقابلا للمراجعة والتقدم عبر نقاط الفحص.",
      "الموضع الحالي",
      "أكمل الإعداد لتحديد موقعك في المنهج.",
      "مراجعة",
      "حالي",
      "مقفل",
      "تظهر اختبارات التقدم كميزات نموذجية. في الإنتاج تتطلب تسجيلا واحدا، وإعادة واحدة، وعدم وجود ألم.",
    ],
    journal: [
      "السجل",
      "دليل مقابل آخر تسجيل.",
      "يحفظ Rehear مقارنات محلية لا كومة تسجيلات خام. كل إدخال يحتفظ بالتسجيل الأول والإعادة وملاحظة واحدة.",
      "لا توجد مقارنات محفوظة بعد.",
      "أكمل تدريب اليوم لحفظ التسجيل الأول ونتيجة الإعادة وملاحظة.",
      "أحدث مقارنة",
      "التسجيل الأول",
      "إعادة",
      "الأول",
      "محفوظ محليا",
      "لا URI",
      "نقاط فحص شهرية",
      "الشهر 1 التنفس والرنين",
      "الشهر 2 التحكم الصوتي",
      "الشهر 3 مقارنة الأغنية النهائية",
      "مفتوح",
      "لاحقا",
    ],
    settings: [
      "الإعدادات",
      "اجعل الوعد واقعيا.",
      "هذه التحكمات تضبط ضغط العادة دون تغيير المنهج الثابت.",
      "تدريب يومي",
      "وقت التذكير",
      "نغمة الإشعار",
      "مدة الجلسة",
      "قواعد العادة",
      "يمكن استخدام يوم سماح واحد لكل شهر. تبقى السلسلة ولا تعاد رحلة 90 يوما.",
      "السلسلة الحالية",
      "أفضل سلسلة",
      "أخرى",
      "تذكير السلامة",
      "توقف إذا آلمك الحلق",
      "اللغة",
      "الصوت",
      "تسجيل محلي حقيقي",
      "حلل ملف صوت",
      "أرسل إلى محلل الرنين",
      "نتيجة التحليل",
      "فشل التحليل",
      "شغّل خادم التحليل وحاول مجددا بملف صوت.",
      "رفض الخادم resonance_vowel، لذلك أعاد Rehear المحاولة مع mmm_resonance.",
      "بانتظار تحليل الخادم. سيظهر تلميح قريبا.",
      "الخادم غير متاح، لذلك استخدم Rehear الملاحظات المحلية.",
      "نتيجة تحليل الإعادة",
      "نتيجة تحليل التسجيل الأول",
      "حذف الحساب",
      "الأذونات",
      "الإشعارات",
      "الميكروفون",
      "مسموح",
      "مرفوض",
      "غير مضبوط",
    ],
  },
  id: {
    tabs: ["Hari ini", "Perjalanan", "Jurnal", "Pengaturan"],
    common: [
      "Hari",
      "dari",
      "Minggu",
      "Memuat perjalanan Rehear...",
      "kelonggaran",
      "Siap",
      "Dipakai",
      "hari ini",
      "streak",
      "streak hari",
      "hari longgar",
      "take pertama",
      "ulang",
    ],
    today: [
      "Sesi latihan",
      "Suara berubah lewat pengulangan kecil yang jujur. Hari ini rekam sekali, perbaiki satu hal, lalu ulangi latihan yang sama.",
      "Pemanasan",
      "Latihan utama",
      "Aturan ulang",
      "Tugas sama, satu petunjuk, satu perbandingan.",
      "Mulai rekam",
      "Rekam take pertama.",
      "Rehear menyimpan take ini di perangkat untuk perbandingan ulang.",
      "Siap merekam",
      "Mulai take pertama",
      "Stop take pertama",
      "Satu hal untuk dicoba.",
      "Yang terdengar",
      "Artinya sering",
      "Satu perbaikan",
      "Ulangi latihan sama",
      "Ulang tanpa ubah.",
      "Latihan sama. Target sama. Hanya petunjuk berubah.",
      "Perbandingan take kedua",
      "Siap ulang",
      "Mulai ulang",
      "Stop ulang",
      "Hari selesai.",
      "Perbandingan disimpan ke Jurnal.",
      "Take terekam",
      "Kembali ke Hari ini",
      "Sesi hari ini",
      "Rekam, dapat satu petunjuk, ulang.",
      "Latihan lagi",
      "Mulai latihan",
      "Mikrofon tidak tersedia",
      "Izinkan mikrofon untuk merekam take nyata.",
      "Setup mikrofon gagal. Alur tetap bisa dilihat, tapi rekaman nyata tidak tersedia.",
      "Rekaman tidak bisa dimulai. Cek izin mikrofon dan coba lagi.",
      "Rekaman tidak bisa disimpan. Coba take yang lebih pendek.",
      "Onboarding merekomendasikan titik awal ini di roadmap tetap.",
    ],
    journey: [
      "Roadmap 3 bulan",
      "Perjalanan Rehear tetapmu.",
      "Onboarding memilih titik awalmu. Jalur 12 minggu tetap terlihat, bisa ditinjau, dan bisa maju lewat checkpoint.",
      "Penempatan saat ini",
      "Selesaikan onboarding untuk menempatkan dirimu di kurikulum.",
      "Tinjau",
      "Saat ini",
      "Terkunci",
      "Cek loncat ditampilkan sebagai fitur prototipe. Di produksi perlu satu rekaman, satu ulang, dan laporan tanpa nyeri.",
    ],
    journal: [
      "Jurnal",
      "Bukti terhadap take terakhirmu.",
      "Rehear menyimpan perbandingan take lokal, bukan tumpukan rekaman mentah. Tiap entri menyimpan take pertama, ulang, dan satu observasi.",
      "Belum ada perbandingan tersimpan.",
      "Selesaikan loop latihan hari ini untuk menyimpan take pertama, hasil ulang, dan observasi.",
      "Perbandingan terbaru",
      "Take pertama",
      "Ulang",
      "Pertama",
      "tersimpan lokal",
      "tanpa URI",
      "Checkpoint bulanan",
      "Bulan 1 napas dan resonansi",
      "Bulan 2 kontrol vokal",
      "Bulan 3 perbandingan lagu final",
      "Buka",
      "Nanti",
    ],
    settings: [
      "Pengaturan",
      "Jaga janji tetap realistis.",
      "Kontrol ini menyesuaikan tekanan kebiasaan tanpa mengubah kurikulum tetap.",
      "Latihan harian",
      "Waktu pengingat",
      "Nada notifikasi",
      "Panjang sesi",
      "Aturan kebiasaan",
      "Satu hari terlewat per bulan bisa memakai hari longgar. Streak bertahan; perjalanan 90 hari tidak reset.",
      "streak saat ini",
      "streak terbaik",
      "Lainnya",
      "Pengingat keamanan",
      "Berhenti jika tenggorokan sakit",
      "Bahasa",
      "Audio",
      "Rekaman lokal nyata",
      "Analisis file audio",
      "Kirim file ke analyzer resonansi",
      "Hasil analisis",
      "Analisis gagal",
      "Nyalakan server analisis dan coba lagi dengan file audio.",
      "Server menolak resonance_vowel, jadi Rehear mencoba lagi dengan mmm_resonance.",
      "Menunggu analisis server. Satu petunjuk segera muncul.",
      "Server tidak tersedia, jadi Rehear memakai fallback lokal.",
      "Hasil analisis ulang",
      "Hasil analisis take pertama",
      "Hapus akun",
      "Izin",
      "Notifikasi",
      "Mikrofon",
      "Diizinkan",
      "Ditolak",
      "Belum diatur",
    ],
  },
};

function buildCompactMainText(pack: CompactMainPack): MainAppText {
  return mergeMainText({
    tabs: {
      today: pack.tabs[0],
      journey: pack.tabs[1],
      coach: "Coach",
      journal: "Milestones",
      settings: pack.tabs[3],
    },
    common: {
      day: pack.common[0],
      of: pack.common[1],
      week: pack.common[2],
      loading: pack.common[3],
      grace: pack.common[4],
      ready: pack.common[5],
      used: pack.common[6],
      today: pack.common[7],
      streak: pack.common[8],
      dayStreak: pack.common[9],
      graceDay: pack.common[10],
      firstTake: pack.common[11],
      retry: pack.common[12],
    },
    today: {
      trainingSession: pack.today[0],
      introBody: pack.today[1],
      warmUp: pack.today[2],
      mainDrill: pack.today[3],
      retryRule: pack.today[4],
      retryRuleDetail: pack.today[5],
      startRecording: pack.today[6],
      recordFirstTake: pack.today[7],
      storesLocally: pack.today[8],
      readyToRecord: pack.today[9],
      startFirstTake: pack.today[10],
      stopFirstTake: pack.today[11],
      oneThing: pack.today[12],
      whatWeHeard: pack.today[13],
      whatItMeans: pack.today[14],
      oneFix: pack.today[15],
      retrySameDrill: pack.today[16],
      retryUnchanged: pack.today[17],
      retryBody: pack.today[18],
      secondTakeComparison: pack.today[19],
      readyToRetry: pack.today[20],
      startRetry: pack.today[21],
      stopRetry: pack.today[22],
      dayComplete: pack.today[23],
      savedFallback: "The app saved this progress to Milestones.",
      recordedTakes: pack.today[25],
      backToToday: pack.today[26],
      todaysSession: pack.today[27],
      recordCueRetry: pack.today[28],
      practiceAgain: pack.today[29],
      startTraining: pack.today[30],
      micUnavailableTitle: pack.today[31],
      micUnavailableBody: pack.today[32],
      micSetupFailed: pack.today[33],
      recordStartFailed: pack.today[34],
      recordSaveFailed: pack.today[35],
      placementReason: pack.today[36],
    },
    journey: {
      kicker: pack.journey[0],
      title: pack.journey[1],
      body: pack.journey[2],
      currentPlacement: pack.journey[3],
      completeOnboarding: pack.journey[4],
      review: pack.journey[5],
      current: pack.journey[6],
      locked: pack.journey[7],
      note: pack.journey[8],
    },
    journal: {
      kicker: "Milestones",
      title: "Achievements from steady practice.",
      body: "Rehear turns completed exercises, daily goals, streaks, and checkpoints into local progress badges.",
      emptyTitle: "No achievements earned yet.",
      emptyBody:
        "Complete today’s training loop to start unlocking exercise, goal, and streak badges.",
      latestComparison: "Latest badge",
      firstTake: pack.journal[6],
      retry: pack.journal[7],
      first: pack.journal[8],
      savedLocally: pack.journal[9],
      noUri: pack.journal[10],
      monthlyCheckpoints: pack.journal[11],
      checkpointOne: pack.journal[12],
      checkpointTwo: pack.journal[13],
      checkpointThree: pack.journal[14],
      open: pack.journal[15],
      later: pack.journal[16],
    },
    settings: {
      kicker: pack.settings[0],
      title: pack.settings[1],
      body: pack.settings[2],
      dailyTraining: pack.settings[3],
      reminderTime: pack.settings[4],
      notificationTone: pack.settings[5],
      sessionLength: pack.settings[6],
      habitRules: pack.settings[7],
      graceCopy: pack.settings[8],
      currentStreak: pack.settings[9],
      bestStreak: pack.settings[10],
      other: pack.settings[11],
      permissions: pack.settings[28],
      notifications: pack.settings[29],
      microphone: pack.settings[30],
      permissionAllowed: pack.settings[31],
      permissionDenied: pack.settings[32],
      permissionNotSet: pack.settings[33],
      safetyReminder: pack.settings[12],
      safetyReminderValue: pack.settings[13],
      language: pack.settings[14],
      audio: pack.settings[15],
      audioValue: pack.settings[16],
      analyzeAudioFile: pack.settings[17],
      analyzeAudioFileValue: pack.settings[18],
      analyzeAudioTitle: pack.settings[19],
      analyzeAudioFailedTitle: pack.settings[20],
      analyzeAudioFailedBody: pack.settings[21],
      analysisCompatibilityFallback: pack.settings[22],
      waitingForAnalysis: pack.settings[23],
      localFallbackUsed: pack.settings[24],
      retryAnalysisTitle: pack.settings[25],
      firstAnalysisTitle: pack.settings[26],
      deleteAccount: pack.settings[27],
    },
  } as Partial<MainAppText>);
}

export const mainAppText: Record<MainAppLanguage, MainAppText> = {
  en: baseMainAppText.en,
  ko: baseMainAppText.ko,
  es: mergeMainText(localizeMainTree(baseMainAppText.en, "es")),
  pt: buildCompactMainText(compactMainPacks.pt),
  fr: buildCompactMainText(compactMainPacks.fr),
  de: buildCompactMainText(compactMainPacks.de),
  ja: buildCompactMainText(compactMainPacks.ja),
  zhHans: buildCompactMainText(compactMainPacks.zhHans),
  zhHant: buildCompactMainText(compactMainPacks.zhHant),
  hi: buildCompactMainText(compactMainPacks.hi),
  ar: buildCompactMainText(compactMainPacks.ar),
  id: buildCompactMainText(compactMainPacks.id),
};

export function normalizeMainLanguage(language: Language): MainAppLanguage {
  return language;
}

const weekKo: Record<number, { title: string; goal: string }> = {
  1: {
    title: "호흡 인식",
    goal: "밀어내지 않고 일정하게 나가는 숨을 느낍니다.",
  },
  2: { title: "부드러운 소리", goal: "목에 압박 없이 소리를 시작합니다." },
  3: {
    title: "공명 탐색",
    goal: "목에만 걸리지 않는 더 쉬운 울림을 탐색합니다.",
  },
  4: {
    title: "호흡 + 공명 연결",
    goal: "일정한 숨, 부드러운 소리, 울림을 짧은 음으로 연결합니다.",
  },
};

const genericWeekGoal: Record<
  MainAppLanguage,
  Record<CurriculumWeek["phase"], string>
> = {
  en: {
    foundation: "Build steady breath, gentle sound, and easier resonance.",
    control: "Train clean starts, endings, pitch, timing, and small phrases.",
    songs:
      "Apply the same feedback loop to songs, range, expression, and full takes.",
  },
  es: {
    foundation:
      "Construye aire estable, sonido suave y una resonancia más fácil.",
    control: "Entrena comienzos, finales, afinación, ritmo y frases pequeñas.",
    songs:
      "Aplica el mismo ciclo a canciones, rango, expresión y tomas completas.",
  },
  pt: {
    foundation: "Construa ar estável, som suave e ressonância mais fácil.",
    control: "Treine entradas, finais, afinação, ritmo e frases curtas.",
    songs:
      "Aplique o mesmo ciclo a músicas, extensão, expressão e takes completos.",
  },
  fr: {
    foundation:
      "Construisez un souffle stable, un son doux et une résonance plus facile.",
    control:
      "Travaillez les attaques, fins, justesse, rythme et petites phrases.",
    songs:
      "Appliquez la même boucle aux chansons, à la tessiture, à l’expression et aux prises complètes.",
  },
  de: {
    foundation: "Baue ruhigen Atem, sanften Klang und leichtere Resonanz auf.",
    control: "Trainiere Einsätze, Enden, Tonhöhe, Timing und kurze Phrasen.",
    songs:
      "Wende dieselbe Schleife auf Songs, Umfang, Ausdruck und ganze Takes an.",
  },
  ja: {
    foundation: "安定した息、やさしい音、楽な響きを作ります。",
    control: "出だし、終わり、音程、リズム、短いフレーズを練習します。",
    songs: "同じフィードバックループを曲、音域、表現、通し録音に使います。",
  },
  ko: {
    foundation: "일정한 숨, 부드러운 소리, 더 쉬운 공명을 만듭니다.",
    control: "시작, 끝처리, 음정, 박자, 짧은 구절을 훈련합니다.",
    songs: "같은 피드백 루프를 노래, 음역, 표현, 전체 테이크에 적용합니다.",
  },
  zhHans: {
    foundation: "建立稳定气息、柔和声音和更轻松的共鸣。",
    control: "训练起音、收尾、音准、节奏和短句。",
    songs: "把同样的反馈循环应用到歌曲、音域、表达和完整录音。",
  },
  zhHant: {
    foundation: "建立穩定氣息、柔和聲音和更輕鬆的共鳴。",
    control: "訓練起音、收尾、音準、節奏和短句。",
    songs: "把同樣的回饋循環應用到歌曲、音域、表達和完整錄音。",
  },
  hi: {
    foundation: "स्थिर सांस, नरम आवाज़ और आसान अनुनाद बनाएं.",
    control: "शुरुआत, अंत, सुर, टाइमिंग और छोटी पंक्तियां अभ्यास करें.",
    songs: "इसी फीडबैक लूप को गीत, रेंज, अभिव्यक्ति और पूरी टेक पर लगाएं.",
  },
  ar: {
    foundation: "ابن تنفسا ثابتا وصوتا لطيفا ورنينا أسهل.",
    control: "درّب البدايات والنهايات والطبقة والتوقيت والعبارات القصيرة.",
    songs:
      "طبّق حلقة الملاحظات نفسها على الأغاني والمدى والتعبير والتسجيلات الكاملة.",
  },
  id: {
    foundation:
      "Bangun napas stabil, suara lembut, dan resonansi yang lebih mudah.",
    control: "Latih awalan, akhiran, nada, timing, dan frasa pendek.",
    songs:
      "Terapkan loop feedback yang sama ke lagu, rentang, ekspresi, dan take penuh.",
  },
};

export function displayWeek(week: CurriculumWeek, language: MainAppLanguage) {
  if (language !== "en") {
    if (language === "ko" && weekKo[week.weekNumber]) {
      return weekKo[week.weekNumber];
    }

    return {
      title: `${mainAppText[language].common.week} ${week.weekNumber}`,
      goal: genericWeekGoal[language][week.phase],
    };
  }

  return {
    title: week.title,
    goal: week.goal,
  };
}

export function displayPhase(phaseLabel: string, language: MainAppLanguage) {
  if (language === "en") {
    return phaseLabel;
  }

  const labels: Record<MainAppLanguage, Record<string, string>> = {
    en: {},
    es: {
      "Breath & Resonance": "Respiración y resonancia",
      "Vocal Control": "Control vocal",
      "Song Application": "Aplicación en canciones",
    },
    pt: {
      "Breath & Resonance": "Respiração e ressonância",
      "Vocal Control": "Controle vocal",
      "Song Application": "Aplicação em músicas",
    },
    fr: {
      "Breath & Resonance": "Souffle et résonance",
      "Vocal Control": "Contrôle vocal",
      "Song Application": "Application en chanson",
    },
    de: {
      "Breath & Resonance": "Atem und Resonanz",
      "Vocal Control": "Stimmkontrolle",
      "Song Application": "Song-Anwendung",
    },
    ja: {
      "Breath & Resonance": "息と響き",
      "Vocal Control": "声のコントロール",
      "Song Application": "曲への応用",
    },
    ko: {
      "Breath & Resonance": "호흡과 공명",
      "Vocal Control": "보컬 컨트롤",
      "Song Application": "노래 적용",
    },
    zhHans: {
      "Breath & Resonance": "气息与共鸣",
      "Vocal Control": "声音控制",
      "Song Application": "歌曲应用",
    },
    zhHant: {
      "Breath & Resonance": "氣息與共鳴",
      "Vocal Control": "聲音控制",
      "Song Application": "歌曲應用",
    },
    hi: {
      "Breath & Resonance": "सांस और अनुनाद",
      "Vocal Control": "वोकल नियंत्रण",
      "Song Application": "गीत में प्रयोग",
    },
    ar: {
      "Breath & Resonance": "التنفس والرنين",
      "Vocal Control": "التحكم الصوتي",
      "Song Application": "تطبيق الأغاني",
    },
    id: {
      "Breath & Resonance": "Napas dan resonansi",
      "Vocal Control": "Kontrol vokal",
      "Song Application": "Penerapan lagu",
    },
  };

  return labels[language][phaseLabel] ?? phaseLabel;
}

export function displaySessionText(value: string, language: MainAppLanguage) {
  if (language === "en") {
    return value;
  }

  const labels: Record<MainAppLanguage, Record<string, string>> = {
    en: {},
    es: {
      Baseline: "Base",
      Stabilize: "Estabilizar",
      Clarify: "Aclarar",
      Retry: "Reintento",
      Apply: "Aplicar",
      Review: "Revisar",
      Checkpoint: "Checkpoint",
      "Record the current version": "Graba la versión actual",
      "Repeat the easiest version": "Repite la versión más fácil",
      "Add one technical detail": "Añade un detalle técnico",
      "Repeat and compare": "Repite y compara",
      "Use it in a tiny musical pattern": "Úsalo en un patrón musical pequeño",
      "Compare first and latest takes": "Compara la primera y la última toma",
      "Recover, reflect, or advance": "Recupera, reflexiona o avanza",
      "First take": "Primera toma",
      "Small cue": "Pista pequeña",
      "Focused take": "Toma enfocada",
      "Same drill": "Mismo ejercicio",
      "Application take": "Toma aplicada",
      "Best take": "Mejor toma",
      "Gentle check": "Chequeo suave",
      "Quiet inhale": "Inhalación tranquila",
      "Soft hiss": "Siseo suave",
      "10-second air release": "Salida de aire de 10 segundos",
      "Soft hum": "Tarareo suave",
      "Gentle mm": "Mm suave",
      "Comfort check": "Chequeo de comodidad",
      Mmm: "Mmm",
      Nnn: "Nnn",
      Ng: "Ng",
      "Mmm-ah": "Mmm-ah",
      "Hiss to hum": "De siseo a tarareo",
      "Hum to ah": "De tarareo a ah",
      "3-5 second tone": "Tono de 3-5 segundos",
    },
    pt: {
      Baseline: "Base",
      Stabilize: "Estabilizar",
      Clarify: "Clarear",
      Retry: "Repetir",
      Apply: "Aplicar",
      Review: "Revisar",
      Checkpoint: "Checkpoint",
      "Record the current version": "Grave a versão atual",
      "Repeat the easiest version": "Repita a versão mais fácil",
      "Add one technical detail": "Adicione um detalhe técnico",
      "Repeat and compare": "Repita e compare",
      "Use it in a tiny musical pattern": "Use em um pequeno padrão musical",
      "Compare first and latest takes": "Compare a primeira e a última tomada",
      "Recover, reflect, or advance": "Recupere, reflita ou avance",
      "First take": "Primeira tomada",
      "Small cue": "Dica pequena",
      "Focused take": "Tomada focada",
      "Same drill": "Mesmo exercício",
      "Application take": "Tomada aplicada",
      "Best take": "Melhor tomada",
      "Gentle check": "Checagem suave",
      "Quiet inhale": "Inspiração calma",
      "Soft hiss": "Sibilo suave",
      "10-second air release": "Soltar ar por 10 segundos",
      "Soft hum": "Hum suave",
      "Gentle mm": "Mm leve",
      "Comfort check": "Checagem de conforto",
      Mmm: "Mmm",
      Nnn: "Nnn",
      Ng: "Ng",
      "Mmm-ah": "Mmm-ah",
      "Hiss to hum": "Do sibilo ao hum",
      "Hum to ah": "Do hum ao ah",
      "3-5 second tone": "Tom de 3-5 segundos",
    },
    fr: {
      Baseline: "Base",
      Stabilize: "Stabiliser",
      Clarify: "Clarifier",
      Retry: "Reprise",
      Apply: "Appliquer",
      Review: "Réviser",
      Checkpoint: "Point de contrôle",
      "Record the current version": "Enregistrez la version actuelle",
      "Repeat the easiest version": "Répétez la version la plus facile",
      "Add one technical detail": "Ajoutez un détail technique",
      "Repeat and compare": "Répétez et comparez",
      "Use it in a tiny musical pattern":
        "Utilisez-le dans un mini motif musical",
      "Compare first and latest takes":
        "Comparez la première et la dernière prise",
      "Recover, reflect, or advance": "Récupérez, réfléchissez ou avancez",
      "First take": "Première prise",
      "Small cue": "Petit conseil",
      "Focused take": "Prise ciblée",
      "Same drill": "Même exercice",
      "Application take": "Prise appliquée",
      "Best take": "Meilleure prise",
      "Gentle check": "Vérification douce",
      "Quiet inhale": "Inspiration calme",
      "Soft hiss": "Sifflement doux",
      "10-second air release": "Expiration de 10 secondes",
      "Soft hum": "Humming doux",
      "Gentle mm": "Mm léger",
      "Comfort check": "Vérification du confort",
      Mmm: "Mmm",
      Nnn: "Nnn",
      Ng: "Ng",
      "Mmm-ah": "Mmm-ah",
      "Hiss to hum": "Du sifflement au hum",
      "Hum to ah": "Du hum au ah",
      "3-5 second tone": "Son de 3-5 secondes",
    },
    de: {
      Baseline: "Basis",
      Stabilize: "Stabilisieren",
      Clarify: "Klären",
      Retry: "Wiederholen",
      Apply: "Anwenden",
      Review: "Prüfen",
      Checkpoint: "Checkpoint",
      "Record the current version": "Nimm die aktuelle Version auf",
      "Repeat the easiest version": "Wiederhole die leichteste Version",
      "Add one technical detail": "Füge ein technisches Detail hinzu",
      "Repeat and compare": "Wiederholen und vergleichen",
      "Use it in a tiny musical pattern":
        "Nutze es in einem kleinen musikalischen Muster",
      "Compare first and latest takes": "Vergleiche erste und letzte Takes",
      "Recover, reflect, or advance": "Erholen, reflektieren oder weitergehen",
      "First take": "Erster Take",
      "Small cue": "Kleiner Hinweis",
      "Focused take": "Fokussierter Take",
      "Same drill": "Gleiche Übung",
      "Application take": "Anwendungs-Take",
      "Best take": "Bester Take",
      "Gentle check": "Sanfter Check",
      "Quiet inhale": "Ruhig einatmen",
      "Soft hiss": "Sanftes Zischen",
      "10-second air release": "10 Sekunden Luft abgeben",
      "Soft hum": "Sanftes Summen",
      "Gentle mm": "Leichtes mm",
      "Comfort check": "Komfortcheck",
      Mmm: "Mmm",
      Nnn: "Nnn",
      Ng: "Ng",
      "Mmm-ah": "Mmm-ah",
      "Hiss to hum": "Zischen zu Summen",
      "Hum to ah": "Summen zu ah",
      "3-5 second tone": "3-5-Sekunden-Ton",
    },
    ja: {
      Baseline: "基準",
      Stabilize: "安定",
      Clarify: "明確化",
      Retry: "リトライ",
      Apply: "応用",
      Review: "復習",
      Checkpoint: "チェックポイント",
      "Record the current version": "今の状態を録音",
      "Repeat the easiest version": "一番簡単な形を繰り返す",
      "Add one technical detail": "技術ポイントを一つ足す",
      "Repeat and compare": "繰り返して比較",
      "Use it in a tiny musical pattern": "小さな音楽パターンで使う",
      "Compare first and latest takes": "最初と最新のテイクを比較",
      "Recover, reflect, or advance": "回復、振り返り、次へ",
      "First take": "最初のテイク",
      "Small cue": "小さなヒント",
      "Focused take": "集中テイク",
      "Same drill": "同じドリル",
      "Application take": "応用テイク",
      "Best take": "ベストテイク",
      "Gentle check": "やさしい確認",
      "Quiet inhale": "静かな吸気",
      "Soft hiss": "やさしいヒス",
      "10-second air release": "10秒の息吐き",
      "Soft hum": "やさしいハミング",
      "Gentle mm": "軽い mm",
      "Comfort check": "快適さ確認",
      Mmm: "Mmm",
      Nnn: "Nnn",
      Ng: "Ng",
      "Mmm-ah": "Mmm-ah",
      "Hiss to hum": "ヒスからハミング",
      "Hum to ah": "ハミングから ah",
      "3-5 second tone": "3-5秒の音",
    },
    ko: {
      Baseline: "기준 녹음",
      Stabilize: "안정화",
      Clarify: "명확화",
      Retry: "재시도",
      Apply: "적용",
      Review: "복습",
      Checkpoint: "체크포인트",
      "Record the current version": "현재 상태를 녹음합니다",
      "Repeat the easiest version": "가장 쉬운 형태로 반복합니다",
      "Add one technical detail": "기술 힌트 하나를 더합니다",
      "Repeat and compare": "반복하고 비교합니다",
      "Use it in a tiny musical pattern": "아주 작은 음악 패턴에 적용합니다",
      "Compare first and latest takes": "첫 테이크와 최신 테이크를 비교합니다",
      "Recover, reflect, or advance": "회복, 회고, 다음 단계 선택",
      "First take": "첫 테이크",
      "Small cue": "작은 힌트",
      "Focused take": "집중 테이크",
      "Same drill": "같은 드릴",
      "Application take": "적용 테이크",
      "Best take": "최고 테이크",
      "Gentle check": "부드러운 체크",
      "Sustained Hiss": "지속 hiss",
      "Release a steady stream of air without pushing.":
        "밀지 않고 일정한 숨을 내보냅니다.",
      "Inhale quietly, then make a soft hiss that stays even from start to finish.":
        "조용히 들이마신 뒤 처음부터 끝까지 고른 부드러운 hiss를 냅니다.",
      "Gentle Hum": "부드러운 허밍",
      "Start a tiny hum without throat pressure.":
        "목 압박 없이 작은 허밍을 시작합니다.",
      "Hum quietly on one comfortable pitch and stop before it feels pressed.":
        "편안한 한 음에서 조용히 허밍하고 눌리는 느낌 전 멈춥니다.",
      "Soft Hum Start": "부드러운 허밍 시작",
      "Begin sound cleanly without a hard attack.":
        "강한 충격 없이 깨끗하게 소리를 시작합니다.",
      "Let the hum appear gently after the breath; avoid grabbing the first moment.":
        "숨 뒤에 허밍이 부드럽게 나타나게 하고 첫 순간을 잡아당기지 않습니다.",
      "Mmm Resonance": "Mmm 공명",
      "Find an easy buzz without pressing for volume.":
        "소리를 키우려고 누르지 않고 쉬운 울림을 찾습니다.",
      "Use a small mmm and notice whether it feels easier in the lips or face.":
        "작은 mmm로 입술이나 얼굴 쪽이 더 편한지 느껴봅니다.",
      "Fah / Vah Resonance": "Fah / Vah 공명",
      "Keep the same easy resonance on a gentle consonant-vowel.":
        "부드러운 자음-모음에서도 같은 쉬운 공명을 유지합니다.",
      "Speak-sing fah or vah softly, keeping it light and unforced.":
        "fah 또는 vah를 말하듯 부드럽게 내고 가볍게 유지합니다.",
      "Hum to Ah": "허밍에서 Ah",
      "Open from hum to ah without losing ease.":
        "편안함을 잃지 않고 허밍에서 ah로 엽니다.",
      "Start with a gentle hum, then open to ah while keeping the same calm airflow.":
        "부드러운 허밍으로 시작한 뒤 같은 차분한 숨으로 ah를 엽니다.",
      "Short Tone Hold": "짧은 음 유지",
      "Hold a short sound comfortably and finish cleanly.":
        "짧은 소리를 편안하게 유지하고 깨끗하게 끝냅니다.",
      "Sing one easy pitch for 3-5 seconds, then release without squeezing.":
        "쉬운 한 음을 3-5초 내고 조이지 않고 놓습니다.",
      "Quiet inhale": "조용한 들숨",
      "Soft hiss": "부드러운 hiss",
      "10-second air release": "10초 숨 내보내기",
      "Soft hum": "부드러운 허밍",
      "Gentle mm": "가벼운 mm",
      "Comfort check": "편안함 확인",
      Mmm: "Mmm",
      Nnn: "Nnn",
      Ng: "Ng",
      "Mmm-ah": "Mmm-ah",
      "Hiss to hum": "hiss에서 허밍",
      "Hum to ah": "허밍에서 ah",
      "3-5 second tone": "3-5초 짧은 음",
      "Smaller air": "더 적은 숨",
      "Even ending": "고른 끝맺음",
      "Relaxed inhale": "편안한 들숨",
      "Timed release": "시간 맞춘 내보내기",
      Compare: "비교",
      "Easy start": "부드러운 시작",
      "Steady volume": "고른 음량",
      "Short hold": "짧게 유지",
      "Baseline resonance": "공명 기준 녹음",
      "Find vibration": "진동 찾기",
      "Keep it easy": "편안하게 유지",
      "Open gently": "부드럽게 열기",
      "Vowel resonance": "모음 공명",
      "Repeat best sound": "가장 좋은 소리 반복",
      "Baseline tone": "짧은 음 기준 녹음",
      "Softer onset": "더 부드러운 시작",
      "Stable middle": "안정된 중간",
      "Clean ending": "깨끗한 끝맺음",
      "Tiny musical move": "작은 음악 움직임",
      "Month comparison": "한 달 비교",
      "Month 1 checkpoint": "1개월 체크포인트",
      "Record a natural soft hiss": "자연스러운 부드러운 hiss를 녹음합니다",
      "Repeat the hiss with less force": "힘을 줄여 hiss를 반복합니다",
      "Keep the last third from collapsing":
        "마지막 1/3이 무너지지 않게 유지합니다",
      "Avoid shoulder lift and over-breathing": "어깨 들림과 과호흡을 피합니다",
      "Hold a 10-second steady hiss": "10초 동안 고른 hiss를 유지합니다",
      "Compare the first hiss with the latest hiss":
        "첫 hiss와 최신 hiss를 비교합니다",
      "Check whether air can leave without pushing":
        "밀지 않고 숨이 나가는지 확인합니다",
      "Record a tiny comfortable hum": "작고 편안한 허밍을 녹음합니다",
      "Begin the hum without a hard attack": "강한 충격 없이 허밍을 시작합니다",
      "Keep the hum small and even": "허밍을 작고 고르게 유지합니다",
      "Stop before the sound gets pressed": "소리가 눌리기 전에 멈춥니다",
      "Hold a relaxed hum for 3-5 seconds": "편안한 허밍을 3-5초 유지합니다",
      "Compare the first hum with the latest hum":
        "첫 허밍과 최신 허밍을 비교합니다",
      "Check whether sound starts without throat pressure":
        "목 압박 없이 소리가 시작되는지 확인합니다",
      "Record a soft mmm or vah sound":
        "부드러운 mmm 또는 vah 소리를 녹음합니다",
      "Notice easy face or lip vibration":
        "얼굴이나 입술의 편안한 진동을 느껴봅니다",
      "Avoid pressing for more buzz": "더 큰 울림을 만들려고 누르지 않습니다",
      "Open from mmm to ah without grabbing":
        "잡아당기지 않고 mmm에서 ah로 엽니다",
      "Try a gentle fah or vah with the same ease":
        "같은 편안함으로 fah 또는 vah를 시도합니다",
      "Recreate the easiest resonant take":
        "가장 편안했던 공명 테이크를 다시 만듭니다",
      "Check for an easier, less throat-heavy sound":
        "목에 덜 걸리는 편안한 소리인지 확인합니다",
      "Record hum to ah as one connected gesture":
        "허밍에서 ah까지 하나로 이어 녹음합니다",
      "Start the vowel gently without pushing":
        "밀지 않고 모음을 부드럽게 시작합니다",
      "Keep a short tone from wobbling": "짧은 음이 흔들리지 않게 유지합니다",
      "Finish without dropping suddenly": "갑자기 떨어뜨리지 않고 끝냅니다",
      "Keep the same ease on one comfortable pitch":
        "편한 한 음에서 같은 편안함을 유지합니다",
      "Compare the Week 1 sound with today":
        "1주차 소리와 오늘의 소리를 비교합니다",
      "Decide whether to continue, repeat, or advance":
        "계속할지, 반복할지, 다음으로 갈지 정합니다",
      "Use less air than yesterday and keep the hiss narrow, small, and easy.":
        "어제보다 숨을 덜 쓰고 hiss를 좁고 작고 편하게 유지합니다.",
      "Start smaller so the ending can stay alive without adding pressure.":
        "끝까지 살아 있게 하려고 처음을 더 작게 시작합니다.",
      "Take a quiet inhale, then let the hiss begin without a big reset.":
        "조용히 들이마신 뒤 크게 다시 세팅하지 않고 hiss를 시작합니다.",
      "Release only enough air to stay even for the full count.":
        "전체 카운트 동안 고르게 유지될 만큼만 숨을 내보냅니다.",
      "Record the same soft hiss and notice whether it feels easier or steadier.":
        "같은 부드러운 hiss를 녹음하고 더 쉽거나 안정적인지 느껴봅니다.",
      "Make your easiest hiss and decide whether this week feels ready to build on.":
        "가장 쉬운 hiss를 내고 이번 주 감각을 이어가도 될지 정합니다.",
      "Stay on one comfortable pitch and let the hum remain boringly even.":
        "편한 한 음에 머물며 허밍을 지루할 만큼 고르게 유지합니다.",
      "Use a tiny hum and stop the moment the throat wants to help.":
        "아주 작은 허밍을 쓰고 목이 도우려는 순간 멈춥니다.",
      "Keep the hum easy for a few seconds, then release before it tightens.":
        "몇 초 동안 편하게 유지한 뒤 조여지기 전에 놓습니다.",
      "Record the same small hum and notice whether the start feels cleaner.":
        "같은 작은 허밍을 녹음하고 시작이 더 깨끗한지 느껴봅니다.",
      "Begin one gentle hum and decide whether the start feels easy enough to continue.":
        "부드러운 허밍 하나를 시작하고 다음으로 이어갈 만큼 편한지 정합니다.",
      "Keep the mmm quiet and notice the easiest buzz without chasing volume.":
        "mmm을 조용히 유지하고 음량을 쫓지 않은 채 가장 쉬운 울림을 느껴봅니다.",
      "Make the mmm smaller if the throat starts working for the vibration.":
        "진동을 만들려고 목이 일하기 시작하면 mmm을 더 작게 합니다.",
      "Open less than you think and keep the easy hum feeling in the vowel.":
        "생각보다 덜 열고 모음 안에서도 편한 허밍 느낌을 유지합니다.",
      "Choose the sound that felt easiest this week and record that version again.":
        "이번 주 가장 편했던 소리를 골라 그 버전을 다시 녹음합니다.",
      "Record a small resonant sound and decide whether it feels less throat-heavy.":
        "작은 공명 소리를 녹음하고 목에 덜 걸리는지 정합니다.",
      "Let the ah arrive from the hum instead of starting it with extra pressure.":
        "추가 압력으로 ah를 시작하지 말고 허밍에서 ah가 나오게 합니다.",
      "Short gentle tone": "짧은 부드러운 음",
      "Make the tone shorter and finish while it still feels easy.":
        "음을 더 짧게 만들고 아직 편할 때 끝냅니다.",
      "Use one easy pitch: mm, then ah, without changing the calm airflow.":
        "편한 한 음에서 차분한 숨을 바꾸지 않고 mm, 그다음 ah로 이어갑니다.",
      "Record a short easy tone and listen for steadier breath, cleaner start, and easier release.":
        "짧고 쉬운 음을 녹음하고 숨의 안정, 깨끗한 시작, 편한 끝맺음을 들어봅니다.",
      "Record your easiest connected hum-to-ah and decide whether the next month feels appropriate.":
        "가장 편한 hum-to-ah 연결을 녹음하고 다음 달로 넘어갈지 정합니다.",
      "Soft hiss baseline": "부드러운 hiss 기준 녹음",
      "Smaller soft hiss": "더 작은 부드러운 hiss",
      "Even-ending hiss": "끝이 고른 hiss",
      "Quiet inhale to hiss": "조용한 들숨에서 hiss",
      "Timed soft hiss": "시간 맞춘 부드러운 hiss",
      "Hiss comparison take": "hiss 비교 테이크",
      "Breath checkpoint": "호흡 체크포인트",
      "Gentle hum baseline": "부드러운 허밍 기준 녹음",
      "Soft hum start": "부드러운 허밍 시작",
      "Even gentle hum": "고른 부드러운 허밍",
      "Comfort hum": "편안한 허밍",
      "Short gentle hum": "짧은 부드러운 허밍",
      "Hum comparison take": "허밍 비교 테이크",
      "Gentle sound checkpoint": "부드러운 소리 체크포인트",
      "Resonance baseline": "공명 기준 녹음",
      "Mmm resonance": "Mmm 공명",
      "Easy mmm resonance": "편안한 mmm 공명",
      "Mmm-ah connection": "Mmm-ah 연결",
      "Fah or vah resonance": "Fah 또는 vah 공명",
      "Best resonance take": "최고 공명 테이크",
      "Resonance checkpoint": "공명 체크포인트",
      "Hum to ah baseline": "허밍에서 ah 기준 녹음",
      "Soft vowel onset": "부드러운 모음 시작",
      "Clean ending tone": "깨끗한 끝맺음 음",
      "Mm-ah one pitch": "한 음에서 mm-ah",
      "Month 1 comparison": "1개월 비교",
      "Fah / Vah resonance": "Fah / Vah 공명",
    },
    zhHans: {
      Baseline: "基线",
      Stabilize: "稳定",
      Clarify: "明确",
      Retry: "重试",
      Apply: "应用",
      Review: "复习",
      Checkpoint: "检查点",
      "Record the current version": "录下当前版本",
      "Repeat the easiest version": "重复最容易的版本",
      "Add one technical detail": "加入一个技术细节",
      "Repeat and compare": "重复并比较",
      "Use it in a tiny musical pattern": "用于一个小音乐模式",
      "Compare first and latest takes": "比较第一条和最新录音",
      "Recover, reflect, or advance": "恢复、回顾或前进",
      "First take": "第一条录音",
      "Small cue": "小提示",
      "Focused take": "专注录音",
      "Same drill": "同一练习",
      "Application take": "应用录音",
      "Best take": "最佳录音",
      "Gentle check": "轻柔检查",
      "Quiet inhale": "安静吸气",
      "Soft hiss": "轻柔 hiss",
      "10-second air release": "10 秒放气",
      "Soft hum": "轻柔哼鸣",
      "Gentle mm": "轻柔 mm",
      "Comfort check": "舒适度检查",
      Mmm: "Mmm",
      Nnn: "Nnn",
      Ng: "Ng",
      "Mmm-ah": "Mmm-ah",
      "Hiss to hum": "hiss 到哼鸣",
      "Hum to ah": "哼鸣到 ah",
      "3-5 second tone": "3-5 秒声音",
    },
    zhHant: {
      Baseline: "基線",
      Stabilize: "穩定",
      Clarify: "明確",
      Retry: "重試",
      Apply: "應用",
      Review: "複習",
      Checkpoint: "檢查點",
      "Record the current version": "錄下目前版本",
      "Repeat the easiest version": "重複最容易的版本",
      "Add one technical detail": "加入一個技術細節",
      "Repeat and compare": "重複並比較",
      "Use it in a tiny musical pattern": "用於一個小音樂模式",
      "Compare first and latest takes": "比較第一條和最新錄音",
      "Recover, reflect, or advance": "恢復、回顧或前進",
      "First take": "第一條錄音",
      "Small cue": "小提示",
      "Focused take": "專注錄音",
      "Same drill": "同一練習",
      "Application take": "應用錄音",
      "Best take": "最佳錄音",
      "Gentle check": "輕柔檢查",
      "Quiet inhale": "安靜吸氣",
      "Soft hiss": "輕柔 hiss",
      "10-second air release": "10 秒放氣",
      "Soft hum": "輕柔哼鳴",
      "Gentle mm": "輕柔 mm",
      "Comfort check": "舒適度檢查",
      Mmm: "Mmm",
      Nnn: "Nnn",
      Ng: "Ng",
      "Mmm-ah": "Mmm-ah",
      "Hiss to hum": "hiss 到哼鳴",
      "Hum to ah": "哼鳴到 ah",
      "3-5 second tone": "3-5 秒聲音",
    },
    hi: {
      Baseline: "बेसलाइन",
      Stabilize: "स्थिर करें",
      Clarify: "स्पष्ट करें",
      Retry: "दोबारा",
      Apply: "लागू करें",
      Review: "समीक्षा",
      Checkpoint: "चेकपॉइंट",
      "Record the current version": "मौजूदा रूप रिकॉर्ड करें",
      "Repeat the easiest version": "सबसे आसान रूप दोहराएं",
      "Add one technical detail": "एक तकनीकी बात जोड़ें",
      "Repeat and compare": "दोहराएं और तुलना करें",
      "Use it in a tiny musical pattern": "इसे छोटे संगीत पैटर्न में लगाएं",
      "Compare first and latest takes": "पहली और नई टेक की तुलना करें",
      "Recover, reflect, or advance": "आराम करें, सोचें या आगे बढ़ें",
      "First take": "पहली टेक",
      "Small cue": "छोटा संकेत",
      "Focused take": "केंद्रित टेक",
      "Same drill": "वही अभ्यास",
      "Application take": "लागू टेक",
      "Best take": "सबसे अच्छी टेक",
      "Gentle check": "हल्की जांच",
      "Quiet inhale": "शांत सांस अंदर",
      "Soft hiss": "नरम हिस",
      "10-second air release": "10 सेकंड हवा छोड़ना",
      "Soft hum": "नरम हम",
      "Gentle mm": "हल्का mm",
      "Comfort check": "आराम जांच",
      Mmm: "Mmm",
      Nnn: "Nnn",
      Ng: "Ng",
      "Mmm-ah": "Mmm-ah",
      "Hiss to hum": "हिस से हम",
      "Hum to ah": "हम से आ",
      "3-5 second tone": "3-5 सेकंड स्वर",
    },
    ar: {
      Baseline: "خط الأساس",
      Stabilize: "ثبّت",
      Clarify: "وضّح",
      Retry: "إعادة",
      Apply: "طبّق",
      Review: "مراجعة",
      Checkpoint: "نقطة فحص",
      "Record the current version": "سجل النسخة الحالية",
      "Repeat the easiest version": "كرر النسخة الأسهل",
      "Add one technical detail": "أضف تفصيلا تقنيا واحدا",
      "Repeat and compare": "كرر وقارن",
      "Use it in a tiny musical pattern": "استخدمه في نمط موسيقي صغير",
      "Compare first and latest takes": "قارن أول وآخر تسجيل",
      "Recover, reflect, or advance": "استعد، تأمل، أو تقدم",
      "First take": "التسجيل الأول",
      "Small cue": "تلميح صغير",
      "Focused take": "تسجيل مركز",
      "Same drill": "نفس التمرين",
      "Application take": "تسجيل تطبيقي",
      "Best take": "أفضل تسجيل",
      "Gentle check": "فحص لطيف",
      "Quiet inhale": "شهيق هادئ",
      "Soft hiss": "هسيس لطيف",
      "10-second air release": "إخراج هواء 10 ثوان",
      "Soft hum": "همهمة لطيفة",
      "Gentle mm": "مم لطيفة",
      "Comfort check": "فحص الراحة",
      Mmm: "Mmm",
      Nnn: "Nnn",
      Ng: "Ng",
      "Mmm-ah": "Mmm-ah",
      "Hiss to hum": "من الهسيس إلى الهمهمة",
      "Hum to ah": "من الهمهمة إلى آه",
      "3-5 second tone": "نغمة 3-5 ثوان",
    },
    id: {
      Baseline: "Dasar",
      Stabilize: "Stabilkan",
      Clarify: "Perjelas",
      Retry: "Ulang",
      Apply: "Terapkan",
      Review: "Tinjau",
      Checkpoint: "Checkpoint",
      "Record the current version": "Rekam versi saat ini",
      "Repeat the easiest version": "Ulangi versi termudah",
      "Add one technical detail": "Tambahkan satu detail teknik",
      "Repeat and compare": "Ulangi dan bandingkan",
      "Use it in a tiny musical pattern": "Pakai dalam pola musik kecil",
      "Compare first and latest takes": "Bandingkan take pertama dan terbaru",
      "Recover, reflect, or advance": "Pulih, refleksi, atau lanjut",
      "First take": "Take pertama",
      "Small cue": "Petunjuk kecil",
      "Focused take": "Take fokus",
      "Same drill": "Latihan sama",
      "Application take": "Take penerapan",
      "Best take": "Take terbaik",
      "Gentle check": "Cek lembut",
      "Quiet inhale": "Tarik napas tenang",
      "Soft hiss": "Desis lembut",
      "10-second air release": "Lepas udara 10 detik",
      "Soft hum": "Dengung lembut",
      "Gentle mm": "Mm ringan",
      "Comfort check": "Cek nyaman",
      Mmm: "Mmm",
      Nnn: "Nnn",
      Ng: "Ng",
      "Mmm-ah": "Mmm-ah",
      "Hiss to hum": "Desis ke dengung",
      "Hum to ah": "Dengung ke ah",
      "3-5 second tone": "Nada 3-5 detik",
    },
  };

  const [first, second] = value.split(" - ");
  if (second) {
    return `${labels[language][first] ?? first} - ${labels[language][second] ?? second}`;
  }

  return labels[language][value] ?? value;
}

export function displayPreferenceValue(
  value: string,
  language: MainAppLanguage,
) {
  if (language === "en") {
    return value;
  }

  const labels: Record<MainAppLanguage, Record<string, string>> = {
    en: {},
    es: {
      "7:30 PM": "7:30 p. m.",
      "8:00 AM": "8:00 a. m.",
      "1:00 PM": "1:00 p. m.",
      "Choose later": "Elegir más tarde",
      "Coach-like": "Como coach",
      Gentle: "Suave",
      "5 minutes": "5 minutos",
      "10 minutes": "10 minutos",
      "12 minutes": "12 minutos",
      "20 minutes": "20 minutos",
    },
    pt: {
      "7:30 PM": "19:30",
      "8:00 AM": "08:00",
      "1:00 PM": "13:00",
      "Choose later": "Escolher depois",
      "Coach-like": "Como coach",
      Gentle: "Gentil",
      "5 minutes": "5 minutos",
      "10 minutes": "10 minutos",
      "12 minutes": "12 minutos",
      "20 minutes": "20 minutos",
    },
    fr: {
      "7:30 PM": "19:30",
      "8:00 AM": "08:00",
      "1:00 PM": "13:00",
      "Choose later": "Choisir plus tard",
      "Coach-like": "Style coach",
      Gentle: "Doux",
      "5 minutes": "5 minutes",
      "10 minutes": "10 minutes",
      "12 minutes": "12 minutes",
      "20 minutes": "20 minutes",
    },
    de: {
      "7:30 PM": "19:30",
      "8:00 AM": "08:00",
      "1:00 PM": "13:00",
      "Choose later": "Später wählen",
      "Coach-like": "Coach-Stil",
      Gentle: "Sanft",
      "5 minutes": "5 Minuten",
      "10 minutes": "10 Minuten",
      "12 minutes": "12 Minuten",
      "20 minutes": "20 Minuten",
    },
    ja: {
      "7:30 PM": "19:30",
      "8:00 AM": "8:00",
      "1:00 PM": "13:00",
      "Choose later": "後で選ぶ",
      "Coach-like": "コーチ風",
      Gentle: "やさしく",
      "5 minutes": "5分",
      "10 minutes": "10分",
      "12 minutes": "12分",
      "20 minutes": "20分",
    },
    ko: {
      "7:30 PM": "오후 7:30",
      "8:00 AM": "오전 8:00",
      "1:00 PM": "오후 1:00",
      "Choose later": "나중에 선택",
      "Coach-like": "코치 스타일",
      Gentle: "부드럽게",
      "5 minutes": "5분",
      "10 minutes": "10분",
      "12 minutes": "12분",
      "20 minutes": "20분",
    },
    zhHans: {
      "7:30 PM": "19:30",
      "8:00 AM": "08:00",
      "1:00 PM": "13:00",
      "Choose later": "稍后选择",
      "Coach-like": "教练风格",
      Gentle: "温和",
      "5 minutes": "5 分钟",
      "10 minutes": "10 分钟",
      "12 minutes": "12 分钟",
      "20 minutes": "20 分钟",
    },
    zhHant: {
      "7:30 PM": "19:30",
      "8:00 AM": "08:00",
      "1:00 PM": "13:00",
      "Choose later": "稍後選擇",
      "Coach-like": "教練風格",
      Gentle: "溫和",
      "5 minutes": "5 分鐘",
      "10 minutes": "10 分鐘",
      "12 minutes": "12 分鐘",
      "20 minutes": "20 分鐘",
    },
    hi: {
      "7:30 PM": "शाम 7:30",
      "8:00 AM": "सुबह 8:00",
      "1:00 PM": "दोपहर 1:00",
      "Choose later": "बाद में चुनें",
      "Coach-like": "कोच जैसा",
      Gentle: "नरम",
      "5 minutes": "5 मिनट",
      "10 minutes": "10 मिनट",
      "12 minutes": "12 मिनट",
      "20 minutes": "20 मिनट",
    },
    ar: {
      "7:30 PM": "7:30 مساء",
      "8:00 AM": "8:00 صباحا",
      "1:00 PM": "1:00 مساء",
      "Choose later": "اختر لاحقا",
      "Coach-like": "مثل المدرب",
      Gentle: "لطيف",
      "5 minutes": "5 دقائق",
      "10 minutes": "10 دقائق",
      "12 minutes": "12 دقيقة",
      "20 minutes": "20 دقيقة",
    },
    id: {
      "7:30 PM": "19.30",
      "8:00 AM": "08.00",
      "1:00 PM": "13.00",
      "Choose later": "Pilih nanti",
      "Coach-like": "Seperti coach",
      Gentle: "Lembut",
      "5 minutes": "5 menit",
      "10 minutes": "10 menit",
      "12 minutes": "12 menit",
      "20 minutes": "20 menit",
    },
  };

  return labels[language][value] ?? value;
}
